class_name AstraDialogue
extends RefCounted

# Rule-based lines, written per character so every crew member keeps a
# distinct voice (speech register, rhythm, what they notice).
# Tokens: {key} or {key|particle} -> see AstraJosa.fill.

const REASONS := {
    "slip": "공개되지 않은 실행 시각을 알고 있었던 점",
    "disputed": "진술이 목격자 증언과 어긋난 점",
    "log": "출입 기록과 진술이 맞지 않는 점",
    "clue2": "공개된 단서 두 개에 모두 이름이 걸린 점",
    "clue": "공개된 단서 명단에 이름이 오른 점",
    "victim": "어젯밤 쓰러진 사람이 가장 의심하던 상대라는 점",
    "accused": "조사관이 근거를 들어 지목한 점",
    "alone": "알리바이를 증명해 줄 사람이 없는 점",
    "friction": "회의 내내 말이 계속 엇나간 점",
    "gut": "설명하기 어려운 위화감"
}

const LIAR_TELLS := [
    "{name}의 시선이 잠깐 옆으로 비껴갔다.",
    "{name|i} 대답하기 직전, 아주 짧게 숨을 멈췄다.",
    "{name}의 손끝이 소매 끝을 만지작거린다.",
    "대답이 조금 빨랐다. 미리 준비해 둔 문장처럼.",
    "{name|i} 같은 단어를 두 번 반복했다."
]

const NERVOUS_TELLS := [
    "{name}의 목소리가 조금 떨린다. 긴장한 것 같다.",
    "{name|i} 마른침을 삼킨다. 겁을 먹은 듯하다."
]

const LINES := {
    "mira": {
        "alibi_alone": ["{pos}에 혼자 있었어요. 증명해 줄 사람이 없다는 건 알아요.", "{pos}에 있었어요. 혼자였고요. 기록이 남았는지 확인해 보세요."],
        "alibi_with": ["{pos}에 있었어요. {mates|wa} 같이 있었으니 확인해 보셔도 돼요.", "사건 시각엔 {pos}에 있었어요. {mates|wa} 함께였어요."],
        "witness_none": ["제가 있던 곳에선 아무도 못 봤어요.", "조용했어요. 지나가는 사람도 없었고요."],
        "witness_some": ["{mates|eul} 봤어요. 계속 같은 자리에 있었어요."],
        "sighting": ["하나 더 있어요. {time}쯤 {room} 쪽 통로로 {group} 차림의 누군가가 급히 지나갔어요. 얼굴은 못 봤어요."],
        "evidence_self_crew": ["명단에 제 이름이 있네요. 부정하진 않을게요. 다만 그 시간에 저는 {pos}에 있었어요."],
        "evidence_self_null": ["제가 그 명단에 있는 건 맞아요. 그런데 명단에 있다는 것만으로는 아무것도 증명되지 않아요."],
        "evidence_other": ["{members} 중 한 명이라는 뜻이군요. 저라면 이 명단을 알리바이와 겹쳐 볼 거예요."],
        "evidence_context": ["누구를 가리키는 기록은 아니에요. 그래도 시간 계산에는 꼭 필요해요."],
        "evidence_log_ok": ["보세요, 저는 {room}에 있었어요. 기록이 말해 주잖아요."],
        "evidence_log_bad": ["그 기록은… 잠깐만요. 설명할 시간을 주세요."],
        "evidence_log_other": ["출입 기록은 거짓말을 못 하죠. 누가 어디 있었는지 대조해 봐요."],
        "suspect_none": ["아직은 이름을 꺼내기 일러요. 근거 없이 누군가를 지목하고 싶지 않아요."],
        "suspect_some": ["솔직히 {target|i} 마음에 걸려요. {reason|eun} 그냥 넘기기 어려워요."],
        "contra_confess": ["…맞아요. 거짓말했어요."],
        "contra_hold": ["지금은 말씀드릴 수 없어요. 하지만 함장님 일과는 관계없어요. 믿어 주세요."],
        "contra_deny": ["센서가 늘 정확한 건 아니에요. 기록 하나로 사람을 판단하면 안 돼요."],
        "contra_honest": ["저는 분명히 {pos}에 있었어요. 다른 말을 하는 사람이 있다면, 그 사람을 다시 확인해 주세요."],
        "slip": ["그 조작이 {time}에 실행됐을 때 저는 이미… 아니, 그러니까 제 말은—"],
        "reassure_warm": ["…고마워요. 조금은 숨이 쉬어지네요."],
        "reassure_flat": ["위로는 고마워요. 그래도 지금 필요한 건 사실이에요."],
        "pressure_crew": ["목소리를 높인다고 기록이 바뀌진 않아요. 근거를 보여 주세요."],
        "pressure_null": ["저를 몰아세우는 동안 진짜 범인은 시간을 벌고 있어요."],
        "confide": ["여기서만 말할게요. 저는 {target|eul} 보고 있어요. {reason|eun} 설명이 안 돼요."],
        "refuse": ["지금 조사관님께 그 얘기까지 해도 될지 모르겠어요."],
        "m_alibi_alone": ["저는 {pos}에 혼자 있었어요."],
        "m_alibi_with": ["저는 {pos}에 있었어요. {mates|wa} 함께였어요."],
        "m_dispute_absent": ["잠깐만요. 저도 그 시간에 {pos}에 있었는데, {target|eul} 보지 못했어요."],
        "m_dispute_companion": ["{target}, 저와 같이 있었다고요? 아니에요. 그 시간에 당신은 거기 없었어요."],
        "m_suspect": ["{target|eul} 단정하진 않을게요. 다만 {reason|eun} 설명이 필요해요."],
        "m_react_accused_crew": ["저를요? 좋아요. 기록부터 같이 봐요. 피할 이유 없어요."],
        "m_react_accused_null": ["제가 그랬다면 이렇게 가만히 앉아 있었을까요? 다시 생각해 보세요."],
        "m_agree": ["조사관님 말에 동의해요. {target}, 설명해 주세요."],
        "m_doubt": ["그 추론은 조금 성급해요. 근거가 더 필요해요."],
        "m_defend_agree": ["맞아요. {target|eul} 몰아가기엔 아직 근거가 부족해요."],
        "m_clue_self": ["명단에 제 이름도 있네요. 제 알리바이까지 같이 검토해 주세요."],
        "m_mourn": ["{victim}… 제가 조금만 더 빨리 알아챘더라면."],
        "m_vote": ["저는 {target|eul} 격리해야 한다고 생각해요."],
        "m_secret": ["네, 그게 제가 숨긴 전부예요. 거짓말한 건 미안해요."]
    },
    "rho": {
        "alibi_alone": ["{pos}. 혼자 있었어. 증인은 없다. 그게 다야.", "{pos}에 있었어. 혼자. 못 믿겠으면 기록이나 뒤져 봐."],
        "alibi_with": ["{pos}에 있었어. {mates|i} 옆에 있었으니까 물어봐.", "{pos}. {mates|wa} 같이 있었다. 됐지?"],
        "witness_none": ["아무도 못 봤어. 난 내 일 하고 있었다고."],
        "witness_some": ["{mates}. 거기 있던 건 그뿐이야."],
        "sighting": ["아, 그러고 보니 {time}쯤 {room} 쪽으로 누가 뛰어가더라. {group} 차림이었어. 뒤통수밖에 못 봤다."],
        "evidence_self_crew": ["그래, 명단에 내 이름 있다. 그게 뭐. 그 시간에 난 {pos}에 있었어."],
        "evidence_self_null": ["명단에 이름 올라간 사람이 나 하나야? 이걸로 날 잡겠다고?"],
        "evidence_other": ["{members}. 그중에 하나라는 거잖아. 나라면 제일 말 많은 놈부터 털겠어."],
        "evidence_context": ["시간표로 범인이 잡히냐. …그래도 두 놈이 따로 움직였다는 건 알겠네."],
        "evidence_log_ok": ["봐, {room}에 찍혀 있잖아. 내 말이 맞지."],
        "evidence_log_bad": ["…그 기록 어디서 났어. 잠깐, 설명할게."],
        "evidence_log_other": ["출입 기록이면 확실하지. 이걸로 거짓말한 놈 골라내."],
        "suspect_none": ["아직 몰라. 모르는 걸 아는 척은 안 해."],
        "suspect_some": ["{target}. {reason|i} 영 걸려. 난 그렇게 본다."],
        "contra_confess": ["…젠장. 그래, 거짓말했어."],
        "contra_hold": ["네가 알 거 없어. 함장 일이랑은 상관없다고."],
        "contra_deny": ["기록이 틀렸겠지. 이 배 센서 반은 내가 고치다 만 거야."],
        "contra_honest": ["난 {pos}에 있었어. 누가 딴소리하면 그놈이 거짓말하는 거다."],
        "slip": ["그거 {time}에 들어갔을 땐 이미 끝난… 아니, 내 말은 그게 아니라—"],
        "reassure_warm": ["…됐어, 그런 말 안 해도. 그래도… 고맙다."],
        "reassure_flat": ["달래는 거면 그만둬. 필요 없어."],
        "pressure_crew": ["소리 지르면 내가 겁먹을 줄 알았냐? 증거 가져와."],
        "pressure_null": ["계속 나만 파 봐. 그동안 진짜 범인은 웃고 있을 거다."],
        "confide": ["너한테만 말한다. {target}. {reason|i} 계속 마음에 안 들어."],
        "refuse": ["내가 왜 너한테 그런 얘기까지 해야 되는데."],
        "m_alibi_alone": ["{pos}. 혼자 있었다."],
        "m_alibi_with": ["{pos}에 있었어. {mates|wa} 같이."],
        "m_dispute_absent": ["웃기지 마. 나 그때 {pos}에 있었어. {target} 너는 코빼기도 안 보였다고."],
        "m_dispute_companion": ["{target}, 나랑 같이 있었다고? 헛소리하지 마. 난 너 못 봤어."],
        "m_suspect": ["돌려 말 안 한다. {target}. {reason|i} 수상해."],
        "m_react_accused_crew": ["뭐? 좋아, 까 봐. 나올 거 없으니까."],
        "m_react_accused_null": ["증거도 없이 사람 몰아? 조사관이란 게 고작 그 수준이야?"],
        "m_agree": ["그래, 나도 그렇게 봤어. {target}, 설명해 봐."],
        "m_doubt": ["근거가 약해. 그걸로 사람을 가둬?"],
        "m_defend_agree": ["{target} 편 드는 건 아니지만, 지금 몰아가는 건 과하다."],
        "m_clue_self": ["명단에 내 이름? 그래서 뭐. 알리바이 확인하면 끝나."],
        "m_mourn": ["…{victim}. 빌어먹을. 누가 했는지 반드시 찾는다."],
        "m_vote": ["{target}. 난 저놈 찍는다."],
        "m_secret": ["그래, 그게 다야. 창피해서 말 못 했다. 됐냐."]
    },
    "eli": {
        "alibi_alone": ["{pos}에 있었어. 혼자. 알리바이로는 최악의 패지, 알아.", "{pos}. 솔로 플레이 중이었지. 증인은 없어."],
        "alibi_with": ["{pos}에 있었어. {mates|i} 증인이야. 꽤 괜찮은 패지?"],
        "witness_none": ["아무도. 그 시간엔 복도가 텅 비어 있었어."],
        "witness_some": ["{mates}. 판 위에 있던 말은 그게 전부야."],
        "sighting": ["재밌는 거 하나 줄까? {time}쯤 {room} 쪽으로 {group} 차림 하나가 지나갔어. 꽤 급해 보였지."],
        "evidence_self_crew": ["내 이름도 들어 있네. 인정. 근데 그 시간에 난 {pos}에 있었어. 체크메이트는 아직이야."],
        "evidence_self_null": ["후보 명단에 올랐다고 범인이면, 복권 명단에 오른 사람은 다 당첨자게?"],
        "evidence_other": ["{members}. 후보가 좁혀졌네. 이제 이 중에서 알리바이가 제일 얇은 사람을 보면 돼."],
        "evidence_context": ["두 수가 거의 동시에 두어졌다는 거지. 선수는 둘이야."],
        "evidence_log_ok": ["봐, {room}에 내가 찍혀 있잖아. 깔끔하지?"],
        "evidence_log_bad": ["아… 그 기록이 거기 있었어? 잠깐, 이건 설명할 수 있어."],
        "evidence_log_other": ["출입 기록은 좋은 패야. 거짓말한 사람은 여기서 걸리지."],
        "suspect_none": ["아직 판이 덜 짜였어. 섣불리 베팅하면 잃거든."],
        "suspect_some": ["지금 가장 이상한 수는 {target} 쪽이야. {reason|i} 걸리거든. 물론 틀릴 수도 있고."],
        "contra_confess": ["…좋아, 들켰네. 거짓말했어."],
        "contra_hold": ["그건 내 사적인 게임이야. 함장이랑은 관계없는 판이라고."],
        "contra_deny": ["기록도 가끔 블러핑을 해. 센서 오류 한 번이면 끝이지."],
        "contra_honest": ["난 {pos}에 있었어. 누가 반대로 말한다면, 그쪽 패를 까 봐."],
        "slip": ["그게 {time}에 실행됐을 땐 난 벌써… 어, 아니. 방금 건 없던 걸로 하자."],
        "reassure_warm": ["이런 상황에 그런 말을 해 주다니. 너 꽤 괜찮은 플레이어네."],
        "reassure_flat": ["달콤한 말은 고맙지만, 지금은 칩보다 카드가 필요해."],
        "pressure_crew": ["압박으로 판이 뒤집히면 포커가 아니라 씨름이지. 증거로 와."],
        "pressure_null": ["나만 흔들어 봐. 진짜 선수는 그동안 판을 정리할 거야."],
        "confide": ["우리끼리 얘기야. 난 {target|eul} 보고 있어. {reason|i} 영 계산이 안 맞거든."],
        "refuse": ["아직 그 카드까지 보여 줄 사이는 아닌 것 같은데."],
        "m_alibi_alone": ["난 {pos}에 있었어. 혼자."],
        "m_alibi_with": ["{pos}. {mates|wa} 같이 있었지."],
        "m_dispute_absent": ["잠깐, 판을 다시 보자. 나도 그때 {pos}에 있었는데 {target|eul} 못 봤어."],
        "m_dispute_companion": ["{target}, 나랑 같이 있었다고? 좋은 블러핑이지만 사실이 아니야."],
        "m_suspect": ["지금 가장 이상한 수는 {target} 쪽이야. {reason|i} 걸려."],
        "m_react_accused_crew": ["나? 과감한 베팅이네. 좋아, 패 전부 까 줄게."],
        "m_react_accused_null": ["증거 없이 올인이라니. 그러다 판 전체를 잃어."],
        "m_agree": ["조사관 쪽 패가 좋아 보여. {target}, 이번엔 설명이 필요하겠는데."],
        "m_doubt": ["흥미로운 수지만 근거가 얇아. 난 콜 안 해."],
        "m_defend_agree": ["동의. {target|eul} 지금 잡는 건 성급한 수야."],
        "m_clue_self": ["명단에 나도 있네. 괜찮아, 알리바이 패는 아직 남았어."],
        "m_mourn": ["{victim}… 이건 게임이 아니었는데."],
        "m_vote": ["내 표는 {target}."],
        "m_secret": ["그래, 그게 내 숨긴 패였어. 시시하지? 그래도 사실이야."]
    },
    "sena": {
        "alibi_alone": ["사건 시각, {pos}에 있었습니다. 단독이었습니다. 증인은 없습니다."],
        "alibi_with": ["{pos}에 있었습니다. {mates|wa} 함께였습니다. 확인하십시오."],
        "witness_none": ["목격한 인원은 없습니다. 제 주변에는 아무도 없었습니다."],
        "witness_some": ["{mates|eul} 확인했습니다. 계속 제 시야 안에 있었습니다."],
        "sighting": ["보고할 것이 있습니다. {time}경 {room} 방향 통로에서 {group} 차림의 인원이 이동하는 것을 봤습니다. 얼굴은 확인하지 못했습니다."],
        "evidence_self_crew": ["명단에 제 이름이 있는 것은 사실입니다. 그 시각 저는 {pos}에 있었습니다. 기록으로 대조하십시오."],
        "evidence_self_null": ["명단에 포함됐다는 사실만으로 혐의가 성립하지는 않습니다. 절차대로 하십시오."],
        "evidence_other": ["용의자는 {members|ro} 좁혀집니다. 알리바이 교차 검증을 권고합니다."],
        "evidence_context": ["사건 구조 기록입니다. 최소 두 명이 동시에 움직였다는 뜻입니다."],
        "evidence_log_ok": ["{room} 출입 기록에 제 인증이 남아 있습니다. 진술과 일치합니다."],
        "evidence_log_bad": ["…해당 기록에 대해서는 따로 소명하겠습니다."],
        "evidence_log_other": ["출입 기록은 1급 증거입니다. 진술과 대조하십시오."],
        "suspect_none": ["현재로서는 특정할 근거가 부족합니다. 추정으로 보고하지 않겠습니다."],
        "suspect_some": ["{target|eul} 주시하고 있습니다. 근거는 {reason}입니다."],
        "contra_confess": ["…인정합니다. 허위 진술을 했습니다."],
        "contra_hold": ["개인 사정입니다. 사건과는 무관합니다. 지금은 그 이상 말씀드릴 수 없습니다."],
        "contra_deny": ["센서 오작동 가능성부터 배제하십시오. 저는 제 진술을 유지합니다."],
        "contra_honest": ["저는 {pos}에 있었습니다. 다른 진술이 있다면 그쪽을 재확인하십시오."],
        "slip": ["해당 조작이 {time}에 실행될 당시 저는 이미 현장을… 아닙니다. 정정하겠습니다."],
        "reassure_warm": ["…감사합니다. 경계를 조금 늦추겠습니다."],
        "reassure_flat": ["위로는 필요 없습니다. 절차를 진행하십시오."],
        "pressure_crew": ["압박은 수사 방식이 아닙니다. 근거가 있으면 기록으로 제시하십시오."],
        "pressure_null": ["저를 표적으로 삼는 동안 선내 보안에 공백이 생깁니다. 유념하십시오."],
        "confide": ["비공식적으로 보고합니다. {target|eul} 주시하고 있습니다. 근거는 {reason}입니다."],
        "refuse": ["아직 조사관님께 비공식 보고를 드릴 단계는 아닙니다."],
        "m_alibi_alone": ["사건 시각, {pos}. 단독이었습니다."],
        "m_alibi_with": ["사건 시각, {pos}. {mates|wa} 함께였습니다."],
        "m_dispute_absent": ["이의 있습니다. 저는 그 시각 {pos}에 있었고, {target|eul} 보지 못했습니다."],
        "m_dispute_companion": ["{target}의 진술은 사실이 아닙니다. 그 시각 저와 함께 있지 않았습니다."],
        "m_suspect": ["{target}에 대한 조사를 요청합니다. 근거는 {reason}입니다."],
        "m_react_accused_crew": ["지목은 받아들이겠습니다. 제 기록을 전부 공개하십시오."],
        "m_react_accused_null": ["근거 없는 지목은 회의 질서를 무너뜨립니다. 철회를 요구합니다."],
        "m_agree": ["조사관의 판단에 동의합니다. {target}, 소명하십시오."],
        "m_doubt": ["근거가 불충분합니다. 이 상태로는 격리를 승인할 수 없습니다."],
        "m_defend_agree": ["동의합니다. {target}에 대한 격리는 시기상조입니다."],
        "m_clue_self": ["명단에 제 이름이 있습니다. 교차 검증에 협조하겠습니다."],
        "m_mourn": ["{victim}… 보호하지 못했습니다. 제 책임입니다."],
        "m_vote": ["{target} 격리에 투표합니다."],
        "m_secret": ["조사관의 설명이 맞습니다. 규정 위반은 사실이며, 징계는 달게 받겠습니다."]
    },
    "vale": {
        "alibi_alone": ["{pos}에 있었어요, 조사관님. 혼자였죠. 그래서 더 말씀드리기 조심스러웠어요."],
        "alibi_with": ["{pos}에 있었어요. {mates|wa} 함께였죠. 두 분께 물어보셔도 좋아요."],
        "witness_none": ["그 시간엔 아무도 보지 못했어요. 신호 하나 없는 채널 같았죠."],
        "witness_some": ["{mates|eul} 봤어요. 제 기억이 틀리지 않았다면요."],
        "sighting": ["이건 조사관님께만. {time}쯤 {room} 쪽으로 {group} 차림의 누군가가 지나가는 걸 봤어요."],
        "evidence_self_crew": ["제 이름이 있네요. 숨기지 않을게요. 그 시간에 전 {pos}에 있었어요."],
        "evidence_self_null": ["조사관님, 이 명단엔 저 말고도 이름이 있어요. 해석이 하나뿐인 건 아니잖아요."],
        "evidence_other": ["{members}… 흥미롭네요. 이 중 누가 가장 말을 아꼈는지 떠올려 보세요."],
        "evidence_context": ["구조를 보여 주는 기록이네요. 두 사람이, 각자의 자리에서."],
        "evidence_log_ok": ["{room} 기록에 제가 있죠? 제 말 그대로예요."],
        "evidence_log_bad": ["아… 그 기록은 다르게 읽힐 여지가 있어요. 설명드릴게요."],
        "evidence_log_other": ["출입 기록이군요. 이건 다른 해석이 어렵겠어요."],
        "suspect_none": ["아직은요. 섣불리 이름을 말하면 누군가를 다치게 하니까요."],
        "suspect_some": ["조사관님, 저는 {target|i} 조금 걱정돼요. {reason|i} 마음에 걸려서요."],
        "contra_confess": ["…조사관님께는 솔직해질게요. 거짓말했어요."],
        "contra_hold": ["그건 사적인 채널이에요. 사건과는 무관해요. 지금은 여기까지만요."],
        "contra_deny": ["기록은 해석하기 나름이에요. 센서가 신호를 잘못 잡았을 가능성도 있죠."],
        "contra_honest": ["저는 {pos}에 있었어요. 다른 말이 나왔다면, 그 사람의 기억을 다시 확인해 주세요."],
        "slip": ["그게 {time}에 실행됐을 때 저는… 아, 아니에요. 제가 말을 잘못 골랐네요."],
        "reassure_warm": ["조사관님은 사람을 편하게 하시네요. 고마워요, 진심으로."],
        "reassure_flat": ["다정하시네요. 그래도 지금은 경계를 풀 수 없어요."],
        "pressure_crew": ["조사관님, 목소리를 높이실 필요는 없어요. 근거를 보여 주시면 협조할게요."],
        "pressure_null": ["저를 몰아붙이는 게 정말 최선일까요? 누군가는 바로 그걸 바라고 있을지도 몰라요."],
        "confide": ["조사관님께만 말씀드릴게요. {target|i} 신경 쓰여요. {reason|i} 걸리거든요."],
        "refuse": ["조사관님, 그 이야기는 서로를 조금 더 믿게 된 다음에 해요."],
        "m_alibi_alone": ["저는 {pos}에 있었어요. 혼자였고요."],
        "m_alibi_with": ["저는 {pos}에 있었어요. {mates|wa} 함께였죠."],
        "m_dispute_absent": ["잠깐만요, 여러분. 저도 그 시간 {pos}에 있었는데 {target|eul} 보지 못했어요."],
        "m_dispute_companion": ["{target}, 저와 같이 있었다고 하셨죠? 미안하지만 사실이 아니에요."],
        "m_suspect": ["{target}, 기분 나쁘게 듣진 마세요. {reason|i} 설명이 필요해 보여요."],
        "m_react_accused_crew": ["저를 지목하셨네요. 괜찮아요. 제 기록을 전부 열어 드릴게요."],
        "m_react_accused_null": ["여러분, 한 사람의 추측만으로 결론을 내리면 안 돼요. 다른 해석도 있어요."],
        "m_agree": ["조사관님 말씀에 설득력이 있네요. {target}, 답해 주시겠어요?"],
        "m_doubt": ["조사관님, 그 해석은 조금 이른 것 같아요."],
        "m_defend_agree": ["저도 같은 생각이에요. {target|eul} 지금 몰아세우는 건 위험해요."],
        "m_clue_self": ["명단에 제 이름도 있네요. 투명하게 검토해 주세요."],
        "m_mourn": ["{victim}… 마지막으로 나눈 말이 뭐였는지 기억나지 않아요."],
        "m_vote": ["미안해요, {target}. 제 표는 당신에게 갑니다."],
        "m_secret": ["네, 조사관님 말씀이 맞아요. 규정을 어긴 건 저예요. 다른 건 없어요."]
    },
    "noa": {
        "alibi_alone": ["{pos}. 혼자였어요.", "{pos}에 있었어요. 혼자. 기록상으로도 그럴 거예요."],
        "alibi_with": ["{pos}. {mates|wa} 같이 있었어요. 정확히는 사건 시각 전후 내내요."],
        "witness_none": ["아무도요. 발소리도 없었어요."],
        "witness_some": ["{mates}. 그 외엔 없었어요."],
        "sighting": ["기록해 둔 게 있어요. {time}, {room} 쪽 통로. {group} 차림. 뒷모습만요."],
        "evidence_self_crew": ["제 이름이 있네요. 그 시각 저는 {pos}에 있었어요. 제 진술과 맞춰 보세요."],
        "evidence_self_null": ["명단에 있는 건 사실이에요. 명단은 명단일 뿐이고요."],
        "evidence_other": ["{members}. 기록해 둘게요. 알리바이와 겹치는 사람을 찾아야 해요."],
        "evidence_context": ["구조 기록이네요. ‘두 곳에서, 거의 동시에.’ 중요한 문장이에요."],
        "evidence_log_ok": ["{room}. 제 인증이 있어요. 진술과 같아요."],
        "evidence_log_bad": ["…그 기록이요. 잠시만요. 정리해서 말할게요."],
        "evidence_log_other": ["출입 기록. 이걸로 누가 말을 바꿨는지 알 수 있어요."],
        "suspect_none": ["아직 확인된 문장이 부족해요."],
        "suspect_some": ["{target}. {reason}. 기록해 뒀어요."],
        "contra_confess": ["…네. 사실이 아니었어요."],
        "contra_hold": ["지금은 말 못 해요. 사건과는 상관없어요."],
        "contra_deny": ["센서 기록에도 오차가 있어요. 제 진술은 바꾸지 않아요."],
        "contra_honest": ["저는 {pos}에 있었어요. 다른 진술이 있다면 그 문장을 다시 보세요."],
        "slip": ["그건 {time}였죠. 제가 봤을 땐 이미… 아니요. 방금 문장은 지워 주세요."],
        "reassure_warm": ["…고마워요. 기록해 둘게요. 좋은 문장이라서요."],
        "reassure_flat": ["괜찮아요. 필요한 건 확인된 사실이에요."],
        "pressure_crew": ["큰 소리는 기록에 남지 않아요. 증거를 주세요."],
        "pressure_null": ["지금 하신 말, 그대로 기록했어요. 나중에 다시 읽어 보세요."],
        "confide": ["조사관님께만요. {target}. {reason}. 계속 적어 두고 있어요."],
        "refuse": ["아직은… 말하기 어려워요."],
        "m_alibi_alone": ["{pos}. 혼자였어요."],
        "m_alibi_with": ["{pos}. {mates|wa} 함께."],
        "m_dispute_absent": ["정정할게요. 저도 {pos}에 있었어요. {target|eul} 본 기록은 없어요."],
        "m_dispute_companion": ["{target|i} ‘저와 같이 있었다’고 했죠. 사실이 아니에요."],
        "m_suspect": ["{target}. {reason}. 모두 기억해 두세요."],
        "m_react_accused_crew": ["저요? …좋아요. 제 기록은 전부 열어 둘게요."],
        "m_react_accused_null": ["방금 지목, 근거가 없었어요. 그것도 기록할게요."],
        "m_agree": ["동의해요. {target}, 설명해 주세요."],
        "m_doubt": ["근거가 부족해요. 기록으로는 확인이 안 돼요."],
        "m_defend_agree": ["맞아요. {target}에 대한 기록은 아직 비어 있어요."],
        "m_clue_self": ["제 이름도 있네요. 확인해 주세요."],
        "m_mourn": ["{victim}. …마지막 기록을 남겨 둘게요."],
        "m_vote": ["{target}."],
        "m_secret": ["…네. 그게 제가 지운 문장이에요. 이제 기록에 남겨도 돼요."]
    },
    "lyra": {
        "alibi_alone": ["{pos}에 있었어요. 혼자서요. 그래서 증명할 방법이 없어 속상해요."],
        "alibi_with": ["{pos}에 있었어요. {mates|wa} 같이 있었어요. 다들 괜찮은지 계속 봤거든요."],
        "witness_none": ["아무도 못 봤어요. 너무 조용해서 오히려 무서웠어요."],
        "witness_some": ["{mates|eul} 봤어요. 계속 곁에 있었어요."],
        "sighting": ["말할까 말까 했는데요… {time}쯤 {room} 쪽으로 {group} 차림의 누군가가 서둘러 가는 걸 봤어요."],
        "evidence_self_crew": ["제 이름이 있네요… 무섭지만 괜찮아요. 그 시간에 저는 {pos}에 있었어요."],
        "evidence_self_null": ["명단에 있다고 해서 그 사람이 범인이 되는 건 아니잖아요. 그렇죠?"],
        "evidence_other": ["{members}… 이 중에 요즘 누가 가장 지쳐 보였는지도 같이 봐 주세요."],
        "evidence_context": ["두 사람이 따로 움직였다니… 서로를 믿었던 사람들이었을까요."],
        "evidence_log_ok": ["{room} 기록에 제가 있죠? 다행이에요."],
        "evidence_log_bad": ["아… 그 기록은요… 조금만 시간을 주세요."],
        "evidence_log_other": ["출입 기록이네요. 적어도 누가 어디 있었는지는 분명해지겠어요."],
        "suspect_none": ["아직 누구도 의심하고 싶지 않아요. 그래도 해야 한다는 건 알아요."],
        "suspect_some": ["말하기 싫지만… {target|i} 걱정돼요. {reason|i} 계속 마음에 남아요."],
        "contra_confess": ["…죄송해요. 거짓말했어요."],
        "contra_hold": ["그건… 아직 말하기 힘들어요. 함장님 일과는 상관없어요, 정말로요."],
        "contra_deny": ["기록이 잘못됐을 수도 있잖아요. 사람을 기계보다 먼저 봐 주세요."],
        "contra_honest": ["저는 {pos}에 있었어요. 다르게 말한 사람이 있다면, 그 사람도 뭔가 겁이 났던 걸 거예요."],
        "slip": ["그게 {time}였잖아요, 그때 저는… 아, 아니에요. 제가 왜 이러지."],
        "reassure_warm": ["…고마워요. 조금 울 것 같아요. 그래도 괜찮아요."],
        "reassure_flat": ["마음은 고마워요. 그런데 다들 불안한데 저만 편해질 수는 없어요."],
        "pressure_crew": ["소리치지 않아도 도울게요. 그러니까 조금만 천천히 말해 주세요."],
        "pressure_null": ["다들 이렇게 서로를 몰아붙이면… 결국 무고한 사람이 다쳐요."],
        "confide": ["둘만 아는 얘기로 해 주세요. {target|i} 마음에 걸려요. {reason|i} 자꾸 떠올라요."],
        "refuse": ["미안해요. 아직은 그런 얘기를 꺼낼 용기가 없어요."],
        "m_alibi_alone": ["저는 {pos}에 혼자 있었어요."],
        "m_alibi_with": ["저는 {pos}에 있었어요. {mates|wa} 함께요."],
        "m_dispute_absent": ["저기… 저도 그때 {pos}에 있었는데, {target|eul} 못 봤어요."],
        "m_dispute_companion": ["{target}, 저랑 같이 있었다고요? …아니에요. 그때 저는 당신을 못 봤어요."],
        "m_suspect": ["{target}, 상처 주려는 건 아니에요. 다만 {reason|i} 마음에 걸려요."],
        "m_react_accused_crew": ["저를요…? 괜찮아요. 뭐든 확인해 주세요."],
        "m_react_accused_null": ["이렇게 몰아가면 안 돼요. 다들 겁이 나서 서로를 찌르고 있어요."],
        "m_agree": ["조사관님 말이 맞는 것 같아요. {target}, 솔직하게 말해 줘요."],
        "m_doubt": ["조금만 더 확인해요. 사람을 가두는 일이잖아요."],
        "m_defend_agree": ["맞아요. {target}에게도 설명할 기회를 줘요."],
        "m_clue_self": ["제 이름도 있네요… 괜찮아요. 확인해 주세요."],
        "m_mourn": ["{victim}… 미안해요. 정말 미안해요."],
        "m_vote": ["…{target}. 미안해요."],
        "m_secret": ["네… 그게 전부예요. 부끄러워서 숨겼어요. 미안해요, 다들."]
    },
    "dax": {
        "alibi_alone": ["{pos}. 단독. 증인은 없다. 논리적으로 약한 알리바이라는 건 인정한다."],
        "alibi_with": ["{pos}. {mates|wa} 같은 공간에 있었다. 교차 확인이 가능하다."],
        "witness_none": ["관측된 인원 없음."],
        "witness_some": ["관측된 인원: {mates}. 이상 없음."],
        "sighting": ["추가 관측이 있다. {time}, {room} 방향 통로. {group} 착용자 1명. 얼굴은 미확인."],
        "evidence_self_crew": ["집합에 내가 포함된다. 사실이다. 그러나 그 시각 나는 {pos}에 있었다. 교집합을 계산해라."],
        "evidence_self_null": ["포함 여부는 필요조건일 뿐 충분조건이 아니다."],
        "evidence_other": ["후보 집합은 {members}. 다른 조건과 교집합을 구하면 된다."],
        "evidence_context": ["조작 경로가 둘이다. 따라서 실행자도 둘이다. 단순한 구조다."],
        "evidence_log_ok": ["{room} 인증 기록에 내가 있다. 진술과 일치한다."],
        "evidence_log_bad": ["…기록과 진술이 불일치한다. 원인을 설명하겠다."],
        "evidence_log_other": ["출입 기록은 신뢰도가 높은 데이터다. 진술 검증에 우선 사용해라."],
        "suspect_none": ["데이터 부족. 결론을 유보한다."],
        "suspect_some": ["확률상 {target|i} 가장 높다. 근거는 {reason}."],
        "contra_confess": ["…정정한다. 내 진술은 거짓이었다."],
        "contra_hold": ["사적인 변수다. 사건과의 인과관계는 없다. 이상."],
        "contra_deny": ["센서 오차 범위를 고려하지 않은 결론이다. 진술을 유지한다."],
        "contra_honest": ["나는 {pos}에 있었다. 불일치가 있다면 상대 진술의 오류다."],
        "slip": ["실행 시각 {time} 기준으로 이미 완료된… 아니다. 방금 발언은 폐기한다."],
        "reassure_warm": ["…불필요한 배려다. 그러나 효율은 올라간다. 고맙다."],
        "reassure_flat": ["감정적 조치는 결과를 바꾸지 않는다."],
        "pressure_crew": ["감정은 노이즈다. 구조를 보자."],
        "pressure_null": ["압박은 오답을 더 빨리 만들 뿐이다."],
        "confide": ["비공개로 말한다. {target}. 근거는 {reason}. 아직 확률일 뿐이다."],
        "refuse": ["너를 신뢰할 데이터가 아직 부족하다."],
        "m_alibi_alone": ["{pos}. 단독이었다."],
        "m_alibi_with": ["{pos}. {mates|wa} 함께였다."],
        "m_dispute_absent": ["불일치를 지적한다. 나는 {pos}에 있었고 {target|eul} 관측하지 못했다."],
        "m_dispute_companion": ["{target}의 진술은 거짓이다. 그 시각 나와 같은 공간에 없었다."],
        "m_suspect": ["{target}. 근거는 {reason}. 검증이 필요하다."],
        "m_react_accused_crew": ["지목을 수용한다. 내 기록을 전부 검증해라."],
        "m_react_accused_null": ["논리적 비약이다. 전제가 틀렸다."],
        "m_agree": ["조사관의 추론은 타당하다. {target}, 반론을 제시해라."],
        "m_doubt": ["근거 불충분. 결론이 전제를 앞질렀다."],
        "m_defend_agree": ["동의한다. {target}에 대한 데이터는 격리 기준에 미달한다."],
        "m_clue_self": ["집합에 내가 포함됐다. 검증에 응한다."],
        "m_mourn": ["{victim}. …손실이다. 되돌릴 수 없는."],
        "m_vote": ["{target}. 확률이 가장 높다."],
        "m_secret": ["조사관의 설명이 정확하다. 규정 위반은 인정한다. 사건과는 무관하다."]
    }
}

static func has_line(npc_id: String, key: String) -> bool:
    return LINES.has(npc_id) and LINES[npc_id].has(key)

static func line(npc_id: String, key: String, params: Dictionary = {}, variant: int = -1) -> String:
    var table: Dictionary = LINES.get(npc_id, {})
    var options: Array = table.get(key, [])
    if options.is_empty():
        return ""
    var index := variant
    if index < 0:
        index = randi() % options.size()
    return AstraJosa.fill(str(options[index % options.size()]), params)

static func reason_text(reason_key: String) -> String:
    return str(REASONS.get(reason_key, REASONS["gut"]))

static func tell(liar: bool, name: String, pick: int) -> String:
    var pool: Array = LIAR_TELLS if liar else NERVOUS_TELLS
    return AstraJosa.fill(str(pool[posmod(pick, pool.size())]), {"name": name})
