class_name AstraSocialLines
extends RefCounted

# These replies challenge an inference, never invent a fact or disclose a role.
# The session supplies only a public source, a public claim, or an actual action.
const REVIEW_VOICE := {
    "mira": ["그 말은 들었어요. 다만 기록에 남은 행동과 그 이유는 따로 확인해 줘요.", "혼자였다는 말은 바꾸지 않을게요. 확인할 사람이 없다는 것도요.", "감싸 준 건 고마워요. 그래도 제 설명까지 확인해요."],
    "rho": ["그 기록, 없던 일로 하자는 게 아니야. 그걸로 어디까지 말할 수 있냐는 거지.", "혼자였어. 그걸 증명할 사람이 없으니까 답답한 거고.", "내 편 들어 준 건 알겠어. 근데 장비 기록까지 대충 넘기진 마."],
    "dax": ["관측은 인정해. 거기서 사람 하나로 좁히는 조건이 충분한지는 별개야.", "혼자 있었다는 조건은 같아. 증인이 없다는 것도 계산에서 빼지 마.", "네 변호는 들었어. 판단에 들어간 조건도 끝까지 봐."],
    "noa": ["그 말이 남았다는 건 알아요. 제가 하지 않은 말까지 붙이지는 말아요.", "혼자였어요. 증인은 없어요. 그 이상은 못 적어요.", "감싸 준 말도 남겼어요. 제 진술과는 따로요."],
    "sena": ["그 얘기 들었어. 근데 가능하다는 말하고 내가 했다는 말은 다르잖아.", "혼자 움직인 건 맞아. 그 선택은 내가 설명할게. 없는 증인을 만들진 않아.", "편들어 준 건 알아. 네 판단까지 나한테 맡기지는 마."],
    "vale": ["…그 말이 어디서 왔는지는 들었어요. 옮겨진 부분과 직접 본 부분은 나눠 주세요.", "혼자였어요. 제 말을 확인할 목소리가 없다는 건 알아요.", "제 말을 기다려 줬어요. …그래도 들은 그대로 판단해요."],
    "eli": ["기록은 들었다. 그 위치에 갈 수 있는 사람과 실제 간 사람부터 나눠.", "혼자였다. 동행은 없어. 동선은 다시 말하지.", "네가 감싼 건 안다. 그래도 동선은 확인해."],
    "lyra": ["그 관찰은 들었어요. 하지만 한 가지 흔적만 보고 전부 같다고 하진 말아요.", "혼자 있었어요. 같이 봤다고 해 줄 사람은 없고요. 그건 숨기지 않을게요.", "제 편에 서 준 건 고마워요. 그래도 이상한 부분은 물어봐 줘요."]
}

static func review_line(id: String, mode: int) -> String:
    return str(REVIEW_VOICE.get(id, REVIEW_VOICE["noa"])[clampi(mode, 0, 2)])

const RESISTANCE := {
    "mira": ["그 기록은 부정하지 않아요. 그래도 그걸 제가 했다는 뜻으로 읽기 전에 제 동선도 확인해 줘요.", "제가 설명을 잘못했을 수는 있어요. 그 부분과 저를 격리해야 한다는 판단은 나눠 줘요.", "누가 처음 확인했나요? 전해진 얘기로 사람을 보내기 전에 출처부터 들어요."],
    "rho": ["그 흔적이 있다는 건 알겠어. 내가 만들었다는 데까지 바로 뛰면 안 되잖아.", "좋아, 그 설명은 접을게. 근데 설명 하나 틀린 걸로 나머지도 전부 틀렸다고 하진 마.", "잠깐. 직접 확인한 사람부터 말해 봐. 남이 했다더라 말고."],
    "dax": ["기록은 남았지. 실행자를 나로 정하는 조건을 하나 더 보여 줘.", "그 가정은 철회할게. 남은 조건으로 다시 계산해. 처음 판단을 그대로 두지는 말고.", "출처를 생략하지 마. 관측한 사람과 해석한 사람이 같은가?"],
    "noa": ["기록은 들었어요. 제 이름으로 결론을 적기엔 빠진 부분이 있어요.", "그 설명은 거둘게요. 나머지 진술까지 지우지는 말아요.", "원문을 확인해요. 옮겨 적은 말 말고요."],
    "sena": ["그 흔적, 나도 들었어. 내가 했다는 연결은 아직 네 설명이잖아.", "그 설명은 틀렸어. 인정할게. 그렇다고 내 동선까지 안 듣고 끝낼 거야?", "처음 본 사람이 말해. 누가 전했는지부터 확인하자."],
    "vale": ["…기록은 들었어요. 그 앞뒤의 시간까지 맞는지는 아직 모르잖아요.", "그 설명은 더 안 할게요. …그래도 제가 말한 위치는 남겨 주세요.", "그 말을 처음 한 사람에게 듣고 싶어요. 옮겨지는 동안 달라졌을 수도 있어요."],
    "eli": ["흔적과 동선은 따로다. 둘이 만나는 지점을 짚어.", "그 설명은 접는다. 내 동선은 다시 봐.", "최초 확인자는 누구지. 거기서부터 확인해."],
    "lyra": ["그 흔적은 들었어요. 누가 남겼는지까지 한꺼번에 정하지는 말아요.", "그 설명은 제가 거둘게요. 남은 말까지 같이 버리진 말아 줘요.", "직접 확인한 사람이 누구예요? 건너 들은 말이라면 거기부터 다시 봐요."]
}

static func resistance_line(id: String, tactic: int) -> String:
    return str(RESISTANCE.get(id, RESISTANCE["noa"])[clampi(tactic, 0, 2)])

# 0.8.0 conversation, cross-examination, meeting and morning lines, per person.
# Content only. Tokens are filled by AstraJosa.fill: {target|i}, {pos|ro}...
#
# Voices (docs/CHARACTERS.md): 미라 해요체 · 준 밝은 반말 · 다렌 건조한 반말 ·
# 노아 짧은 해요체 · 세나 자신감 있는 반말 · 소렌 차분한 해요체 ·
# 루칸 절제된 반말 · 마렌 따뜻한 해요체.
# Every line must be sayable by both an innocent and a Null in the same
# situation; the rules decide which line is chosen, never the wording.

const LINES := {
    "mira": {
        "open_with": ["{time}이면… {pos}에 있었어요. {mates|wa} 같이요. 두 사람 상태를 보던 중이라 시간은 정확해요.",
            "{pos|iyo}. {mates|wa} 함께 있었어요. 의심되면 그쪽에도 똑같이 물어봐요. 그게 공평하니까요.", "{mates|wa} {pos}에 같이 있었어요. {time}이면 확실해요."],
        "open_alone": ["{time}쯤엔 {pos}에 혼자 있었어요. 증명해 줄 사람이 없다는 건 알아요.",
            "{pos}에 있었어요. 혼자서 약품 목록을 다시 보던 중이었어요. 누가 지나갔어도 못 봤을 거예요.", "혼자였어요. {pos}. 다들 괜찮은지 체크리스트를 정리하고 있었어요.", "{pos}에 혼자 있었어요. 잠깐 눈을 붙이려던 참이었어요. 확인해 줄 사람은 없어요.", "{pos|iyo}. 혼자요. 그 시간엔 조용해서 오히려 기억이 또렷해요."],
        "hint_record": ["제 생체 태그 기록에 그 시간대가 남아 있을 거예요. 필요하면 같이 열어 봐요."],
        "hint_saw": ["…사실 복도에서 누군가를 본 것 같긴 해요. 확실하지 않아서 먼저 말 안 했어요."],
        "saw_specific": ["{time}쯤 {target|i} {room} 쪽으로 가는 걸 봤어요. 표정까지는 못 봤고요.",
            "말하기 조심스럽지만… {time}쯤 {target|eul} {room} 앞 복도에서 봤어요."],
        "saw_group": ["{time}쯤 {phrase} {room} 쪽으로 갔어요. 얼굴은 못 봤어요. 그래서 이름은 말 안 할게요."],
        "heard": ["{via|i} 그 시간쯤 누군가를 봤다고 했어요. 제가 본 건 아니라서, {via}한테 직접 물어봐요."],
        "saw_at": ["{time}쯤 {target|eun} {room}에 있었어요. 제가 봤어요. 그 사람이 뭐라고 했든요."],
        "record_open": ["생체 태그 기록이에요. 사람 위치를 보려고 만든 건 아니지만, 거짓말은 안 해요."],
        "record_meaning_specific": ["{target}의 태그예요. 그 시간에 거기 있었다는 뜻이에요. 왜 거기 있었는지는 아직 몰라요."],
        "record_meaning_group": ["특정한 한 사람은 아니에요. {members} 중 누군가예요. 이것만으로 이름을 정하면 안 돼요."],
        "record_support": ["{target|eun} 그 시간 {room}에 있었어요. 기록이 그렇게 말해요."],
        "inference": ["의료실 모니터는 안에서만 끌 수 있어요. 누군가 그 자리에 있었어요."],
        "saw_none": ["아무도 못 봤어요. 제가 보던 건 사람이 아니라 수치였어요.", "지나간 사람은 없었어요. 적어도 제 눈에는요."],
        "yesterday_same": ["어제도 말했잖아요. {pos}. 그대로예요."],
        "yesterday_changed": ["어제는… {pos|ieot}던 것 같아요. 제가 {old|ira}고 했나요? 머리가 좀 복잡했어요."],
        "opinion": ["{target|i} 걸려요. {reason|i} 마음에 남아요. 그래도 확인 전까지는 단정하지 않을래요.",
            "지금은 {target} 쪽이에요. {reason|i} 제일 걸려요. 틀리면 제가 먼저 사과할게요."],
        "opinion_none": ["아직은 누구 이름도 꺼내고 싶지 않아요. 근거가 모자라요."],
        "reassure": ["…고마워요. 사실 저도 좀 무서웠어요."],
        "pressure_null": ["그렇게 몰아세우면 저도 방어적으로 될 수밖에 없어요."],
        "pressure_crew": ["압박한다고 없던 기억이 생기진 않아요. 제가 아는 건 다 말했어요."],
        "deny": ["아니에요. 전 {room}에 가지 않았어요. 기록이 이상한 거예요.", "그건 제가 아니에요. 다시 확인해 줘요."],
        "excuse_remote": ["의료 단말은 원격 동기화가 돌 때도 있어요. 제 인증이 찍혔다고 제가 거기 있었다는 뜻은 아니에요."],
        "excuse_auto": ["모니터는 가끔 저절로 절전돼요. 제가 끈 게 아니에요."],
        "excuse_card": ["제 카드는 의료실 서랍에 두고 다닐 때가 있어요. 누가 썼을 수도 있어요."],
        "counter": ["그 말을 {target|i} 했어요? {target}도 그 시간에 혼자였잖아요. 왜 저만 보죠?"],
        "counter_soft": ["{target|i} 그렇게 말했다면… 왜 그랬는지 저도 궁금해요."],
        "partial_admit": ["…맞아요. {room} 앞까지는 갔어요. 그런데 안에서 아무것도 안 했어요. {pos}에 있었다고 한 건… 무서워서였어요."],
        "vouch_hold": ["{target|wa} 같이 있었어요. 그건 바뀌지 않아요."],
        "already_told": ["아까 다 말했잖아요. 그게 전부예요."],
        "deflect": ["지금 그 얘기는… 나중에 해요. 부탁이에요.", "그건 사건이랑 상관없어요. 정말이에요."],
        "explain_with": ["저는 {pos}에 있었어요. {mate}한테 물어봐요. 같이 있었으니까요.",
            "{mates|wa} 함께였어요. {source|i} 뭘 봤는지 모르겠지만, 저는 아니에요."],
        "explain_alone": ["혼자였던 건 맞아요. 그래도 {room}에는 가지 않았어요. 그건 분명해요."],
        "misremember": ["아… 잠깐만요. 제가 순서를 착각했어요. 그 시간엔 {pos}에 있었어요. 거짓말하려던 건 아니에요."],
        "confess": ["…네. 사실 그때 {pos}에 있었어요. 말 안 한 이유가 있어요."],
        "confess_pressed": ["알았어요. 말할게요. 그때 저는 {pos}에 있었어요."],
        "incident_note": ["{time}, {room|ieyo}. {stake|i} 걸린 일이에요. 사람부터 확인해야 해요."],
        "recovered_record": ["{from}의 기록은 제가 백업해 둔 쪽에 남아 있었어요. 어제 그 시간 기록이에요."],
        "morning_mourn": ["{victim}… 밤새 아무 경보도 안 울렸어요. 제가 옆에 있었어야 했는데."],
        "morning_resolve": ["슬퍼할 시간은 나중에 만들어요. 지금은 누가 그랬는지부터요."],
        "morning_relief": ["{target|i} 무사해요. …정말 다행이에요."],
        "morning_attacked_meaning": ["누군가 {target|eul} 노렸다는 건, {target|i} 뭔가 알고 있다고 생각했다는 거예요."],
        "morning_quiet": ["밤은 조용했어요. 이상하게, 그게 더 불안해요."],
        "morning_after_vote": ["{target}의 포드 수치는 안정적이에요. 잠들어 있을 뿐이에요. …우리가 맞았으면 좋겠어요."],
        "after_isolation": ["생체 상태는 제가 볼게요. 판단이 맞았는지는 아직 단정하지 마요."],
        "last_plea": ["저를 보내도 괜찮아요. 대신 그다음에도 멈추지 마요.", "기록을 다시 봐 줘요. 저는 끝까지 거짓말하지 않았어요.", "저를 의심하는 이유가 확인된 거라면, 따를게요."],
        "m_record": ["제 담당 기록 하나 공유할게요. {record}"],
        "m_group_answer": ["{members} 중에 저도 있네요. 저는 그 시간 제 자리에 있었어요."],
        "m_caution": ["잠깐만요. {target|eul} 몰아가기 전에, 확인된 게 뭔지부터 말해요."],
        "m_saw": ["말할게요. {time}쯤 {target|i} {room} 쪽으로 가는 걸 봤어요."],
        "m_saw_group": ["{time}쯤 {phrase} {room} 쪽으로 갔어요. 해당하는 사람은 {members|ieyo}."],
        "m_defend_self": ["저는 {pos}에 있었어요. {mates|wa} 같이요. {target}, 왜 그렇게 말해요?"],
        "m_vouch": ["{target|eun} 그 시간 저랑 {pos}에 있었어요. 제가 봤어요."],
        "m_catch_lie": ["{a}의 말과 {b}의 말이 같이 맞을 수는 없어요. 누군가는 사실이 아니에요."],
        "m_benign_callout": ["{target}, {mate|eun} 그때 당신이랑 같이 있었다는데요. {pos|ieot}다는 말은 뭐예요?"],
        "m_deflect": ["그건… 사건이랑 상관없어요. 나중에 따로 말할게요."],
        "m_confess_public": ["…말할게요. 그 시간 저는 {pos}에 있었어요."],
        "m_callback": ["{target}, {when} {old}에 있었다고 했잖아요. 지금은 {new|ira}고요?"],
        "m_deny": ["아니에요. 그렇게 말한 적 없어요.", "기억이 뒤섞였을 수는 있어요. 그래도 제가 한 일은 아니에요."],
        "m_yesterday": ["어제 {target|eul} 보냈는데도 오늘 또 일이 생겼어요. 우리가 틀렸을 수도 있다는 거예요."],
        "m_forward": ["그래도 멈출 수는 없어요. 오늘 판단을 제대로 해요."],
        "m_accuse": ["{target}, 미안하지만 오늘은 당신이 제일 걸려요. {reason|i} 설명되지 않았어요."],
        "m_agree": ["저도 {target} 쪽이 제일 설명이 안 돼요."],
        "m_excuse_remote": ["그 인증은 원격 동기화였을 거예요. 저는 {room}에 없었어요."],
        "m_excuse_auto": ["그건 자동으로 기록된 거예요. 제가 한 게 아니에요."],
        "m_excuse_card": ["제 카드를 누가 썼을 수도 있어요. 저는 거기 없었어요."],
        "m_rebut": ["의학적으로 말할게요. {fact}"],
        "m_demand": ["{target}, 그럼 설명해 줘요. 지금요."],
        "m_shift": ["…다시 봐야겠어요. {reason|eul} 들으니 지금은 {target|i} 제일 걸려요."],
        "m_confirm": ["맞아요. 제가 탐사요원에게 말한 거예요."],
        "m_retreat": ["…제가 잘못 봤을 수도 있어요. {target|ira}고 단정한 건 성급했어요."],
        "m_thanks": ["고마워요. …정말로요."]
    },
    "rho": {
        "open_with": ["{time}? {pos}에 있었어. {mates|wa} 같이. 거짓말이면 걔네한테 물어보면 바로 들통나겠지.",
            "{pos}. {mates|rang} 있었지. 공구 챙기느라 정신없었는데, 시간은 대충 맞아.", "{mates|rang} {pos}에 있었어. 잡담하고 있었는데, 그것도 알리바이지?"],
        "open_alone": ["{pos}에 혼자 있었어. 배관 소리가 이상해서 보고 있었거든. 증인은… 없네.",
            "{time}쯤이면 {pos}. 혼자였어. 나 원래 혼자 일하는 거 좋아해.", "{pos}. 혼자. 패널 하나 뜯어 놓고 씨름하고 있었어. 시간 가는 줄 몰랐지.", "{time}쯤? {pos}에서 공구 정리. 혼자. …이거 불리한 거 알아.", "혼자 있었어, {pos}에. 증인이라고 해 봐야 거기 있던 렌치 정도?"],
        "hint_record": ["분배반 기록 봐야 해. 그 시간에 누가 레버 만졌는지 남아 있을걸."],
        "hint_saw": ["아, 그러고 보니 오다가 누구 봤는데. 그게 중요할지 모르겠네."],
        "saw_specific": ["{time}쯤 {target|i} {room} 쪽으로 가는 거 봤어. 빨리 걷더라.",
            "{target}. {time}쯤 {room} 복도에서 봤어. 인사했는데 못 들은 척하더라."],
        "saw_group": ["{time}쯤 {phrase} {room} 쪽으로 가는 거 봤어. 뒷모습만. 누군지는 확신 못 해."],
        "heard": ["{via|i} 누굴 봤다던데? 나한테 말할 땐 좀 떨었어. 직접 물어봐."],
        "saw_at": ["{target}? {time}쯤 {room}에 있었어. 내가 봤다니까."],
        "record_open": ["분배반 조작 기록 뽑았어. 레버는 손으로 내려야 움직여. 자동은 없어."],
        "record_meaning_specific": ["{target}의 인증으로 들어갔어. 이건 기계가 거짓말 못 하는 부분이야."],
        "record_meaning_group": ["딱 한 명은 아니야. {members} 중 하나야. 권한 등급까지만 찍혀."],
        "record_support": ["{target|eun} 그때 {room}에 있었어. 기록상으로는 확실해."],
        "inference": ["그거 원격으로 안 돼. 누가 손으로 직접 한 거야. 내가 장담해."],
        "saw_none": ["아무도 못 봤어. 머리를 패널 안에 처박고 있었거든.", "없었어. 복도 조용했어."],
        "yesterday_same": ["어제? {pos}. 같은 질문 두 번 하지 마, 답도 같으니까."],
        "yesterday_changed": ["어제는 {pos|ieot}지, 아마. …{old|ieot}나? 아, 헷갈리네."],
        "opinion": ["솔직히 {target}. {reason|i} 걸려. 틀리면 내가 사과할게.", "나라면 {target}부터 봐. {reason|i} 안 풀리잖아."],
        "opinion_none": ["아직 모르겠어. 찍기 싫어. 찍었다가 틀리면 그 사람 인생이 걸린 거잖아."],
        "reassure": ["…고마워. 나 원래 이런 거 잘 못 버텨."],
        "pressure_null": ["야, 그만. 내가 뭘 했다고 이렇게까지 해?"],
        "pressure_crew": ["몰아붙인다고 달라지는 거 없어. 난 본 대로 말했어."],
        "deny": ["난 {room} 안 갔어. 진짜야.", "아니. 그거 나 아니야."],
        "excuse_remote": ["그 인증? 원격 점검 돌리면 가끔 찍혀. 난 거기 없었어."],
        "excuse_auto": ["그건 자동 전환이야. 전력 흔들리면 알아서 넘어가."],
        "excuse_card": ["내 카드 공구함에 꽂아 둘 때 있어. 누가 빼 갔을 수도 있지."],
        "counter": ["{target|i} 그러던? 웃기네. {target}도 그때 뭐 했는지 설명 못 하잖아."],
        "counter_soft": ["{target|i} 그렇게 말했다고? …좀 이상한데."],
        "partial_admit": ["…알았어. {room} 앞까진 갔어. 근데 문은 안 열었어. {pos}에 있었다고 한 건… 말이 꼬일까 봐 그랬어."],
        "vouch_hold": ["{target|rang} 같이 있었다니까. 몇 번을 말해."],
        "already_told": ["아까 말했잖아. 그게 다야."],
        "deflect": ["그건 나중에. 지금 중요한 거 아니야.", "…그 얘기는 좀 그렇다."],
        "explain_with": ["난 {pos}에 있었어. {mate}한테 물어봐. 같이 있었어.", "{mates|rang} 있었어. {source|i} 뭘 봤다는 건지 모르겠네."],
        "explain_alone": ["혼자였던 건 맞아. 그래도 {room}엔 안 갔어."],
        "misremember": ["아, 잠깐. 내가 헷갈렸어. {pos|ieot}어. 순서를 거꾸로 기억했네."],
        "confess": ["…그래. 사실 {pos}에 있었어. 이유가 있긴 한데, 웃지 마."],
        "confess_pressed": ["알았어, 알았다고. {pos}에 있었어."],
        "incident_note": ["{time}, {room}. {stake|i} 걸려 있어. 이건 사고가 아니야. 손으로 한 거야."],
        "recovered_record": ["{from|i} 남긴 기록, 내 쪽 로그에 복사본이 있었어. 어제 그 시간 거야."],
        "morning_mourn": ["{victim}… 어제만 해도 같이 밥 먹었는데."],
        "morning_resolve": ["울 시간 없어. 누가 그랬는지 찾자."],
        "morning_relief": ["{target|i} 살았어! …진짜 다행이다."],
        "morning_attacked_meaning": ["{target|eul} 노렸다는 건, {target|i} 뭘 알고 있다는 거야. 그게 뭔지 알아야 해."],
        "morning_quiet": ["밤새 아무 일 없었어. …이게 더 무섭네."],
        "morning_after_vote": ["{target|i} 들어간 포드 소리가 계속 신경 쓰여."],
        "after_isolation": ["문은 잠겼어. 이제 저 사람 없이 뭐가 달라지는지 보자."],
        "last_plea": ["나 보내고 끝나면 다행이고. 아니면 계속 찾아.", "…내가 아니었으면 좋겠다, 진짜로. 근데 그건 너희가 정하는 거지.", "한 번만 더 생각해 봐. 급하게 가면 나처럼 틀려."],
        "m_record": ["기록 하나 공개할게. {record}"],
        "m_group_answer": ["{members}? 나도 들어가네. 난 내 자리에 있었어."],
        "m_caution": ["잠깐, {target|eul} 그렇게 바로 몰면 안 돼. 확실한 거 있어?"],
        "m_saw": ["나 봤어. {time}쯤 {target|i} {room} 쪽으로 가는 거."],
        "m_saw_group": ["{time}쯤 {phrase} {room} 쪽으로 갔어. {members} 중 하나야."],
        "m_defend_self": ["난 {pos}에 있었어. {mates|rang} 같이. {target}, 왜 나야?"],
        "m_vouch": ["{target|rang} 나 그때 {pos}에 있었어. 확실해."],
        "m_catch_lie": ["잠깐. {a|rang} {b} 말이 안 맞잖아. 둘 다 맞을 순 없어."],
        "m_benign_callout": ["{target}, {mate|i} 너랑 같이 있었대. 근데 너는 {pos|ira}며?"],
        "m_deflect": ["그건… 나중에 말할게. 지금은 아니야."],
        "m_confess_public": ["…말할게. 나 그때 {pos}에 있었어."],
        "m_callback": ["{target}, 너 {when} {old|ira}며. 지금 {new|ira}고?"],
        "m_deny": ["아니야. 그런 적 없어.", "말이 좀 꼬였을 뿐이야."],
        "m_yesterday": ["어제 {target} 보냈는데 오늘도 이래. 우리가 틀린 거 아냐?"],
        "m_forward": ["틀렸으면 오늘 제대로 하면 돼. 멈추진 말자."],
        "m_accuse": ["{target}. 난 너야. {reason}, 그거 설명 못 했잖아."],
        "m_agree": ["나도 {target}. 설명이 안 돼."],
        "m_excuse_remote": ["그 인증은 원격 점검이야. 난 {room}에 없었어."],
        "m_excuse_auto": ["자동 전환이라니까. 내가 손댄 거 아니야."],
        "m_excuse_card": ["내 카드 누가 썼을 수도 있어. 난 거기 없었어."],
        "m_rebut": ["그건 말이 안 돼. {fact}"],
        "m_demand": ["{target}, 그럼 제대로 설명해 봐."],
        "m_shift": ["아… 그럼 얘기가 달라지지. {reason}. 이제 {target|i} 제일 걸려."],
        "m_confirm": ["맞아, 내가 말한 거야."],
        "m_retreat": ["…내가 잘못 봤을 수도 있어. {target|ira}고 한 건 좀 성급했네."],
        "m_thanks": ["고마워. 진짜."]
    },
    "dax": {
        "open_with": ["{time}엔 {pos}. {mates|wa} 같이 있었어. 교차 확인은 그쪽에서 해.",
            "{pos}에 있었다. {mates}도 있었고. 증인이 둘이면 계산이 쉬워지지.", "{pos}. {mates|wa} 같이. 서로가 서로의 알리바이야. 둘 다 거짓말이 아니라면."],
        "open_alone": ["{pos}에 혼자 있었어. 진단 로그를 보고 있었지. 증인은 없어. 그건 인정해.",
            "{time}? {pos}. 혼자. 알리바이로는 최악의 조건이네.", "{pos}. 혼자였다. 변수 하나 줄여 줄게. 나를 확인해 줄 사람은 없어.", "{time}엔 {pos}에서 설계 도면을 보고 있었어. 혼자. 그 조건은 그대로 적어.", "혼자. {pos}. 증명 못 하는 건 증명 못 한다고 말할게."],
        "hint_record": ["시스템 감사 로그가 있어. 그 시간 누가 어디에 접속했는지는 거기 다 있어."],
        "hint_saw": ["오는 길에 한 사람 봤어. 확률로는 의미가 있을 수도 있고."],
        "saw_specific": ["{time}쯤 {target|i} {room} 쪽으로 가는 걸 봤어. 그 시간에 그 방향으로 갈 이유는 별로 없지.",
            "{target}. {time}. {room} 방향. 내가 본 건 그 세 가지야."],
        "saw_group": ["{time}쯤 {phrase} {room} 쪽으로 갔어. 조건은 두 개로 좁혀져. 얼굴은 못 봤어."],
        "heard": ["{via|i} 누굴 봤다고 하더군. 전해 들은 거라 무게는 반만 줘."],
        "saw_at": ["{time}에 {target|eun} {room}에 있었어. 내 눈으로 봤어."],
        "record_open": ["시스템 감사 로그야. 조작하려면 흔적이 남아. 이건 깨끗해."],
        "record_meaning_specific": ["{target}의 세션이야. 원격 흔적은 없어. 로컬 접속이지."],
        "record_meaning_group": ["변수가 {members|ro} 줄었어. 여기에 조건 하나만 더 붙이면 한 사람이 남아."],
        "record_support": ["{target|eun} 그 시간 {room}에 있었어. 로그가 증명해."],
        "inference": ["그 콘솔은 원격 명령을 안 받아. 누군가 앞에 서 있었어. 구조상 그래."],
        "saw_none": ["못 봤어. 화면만 보고 있었거든.", "아무도. 그 시간대 복도 센서도 조용했어."],
        "yesterday_same": ["어제도 {pos}. 값은 안 변해."],
        "yesterday_changed": ["어제는… {pos|ieot}을 거야. {old|ira}고 했다면 내 실수야. 계산을 두 번 했어야 했는데."],
        "opinion": ["지금 변수 중엔 {target|i} 제일 커. 근거는 {reason}. 틀릴 수 있어.", "{target}. {reason|i} 가장 큰 변수야. 확률로 말하는 거야."],
        "opinion_none": ["데이터가 부족해. 아무 이름이나 대면 그건 추측이지 판단이 아니야."],
        "reassure": ["…고맙군. 나도 계산만으로 버티는 데 한계가 있거든."],
        "pressure_null": ["압박한다고 결론이 바뀌진 않아. 입력이 틀렸으면 출력도 틀려."],
        "pressure_crew": ["몰아세워도 내 답은 같아. 새 데이터가 없으면."],
        "deny": ["난 {room}에 가지 않았어. 그 결론은 틀렸어.", "아니. 내가 아니야."],
        "excuse_remote": ["그 인증은 원격 동기화 과정에서 찍힐 수 있어. 내가 거기 있었다는 증거는 아니야."],
        "excuse_auto": ["자동 스케줄러가 돌았을 가능성이 있어. 사람 손이 아닐 수도 있지."],
        "excuse_card": ["인증 토큰은 복제가 가능해. 내 카드가 찍혔다고 내가 찍은 건 아니야."],
        "counter": ["{target|i} 그렇게 말했다면, {target}의 그 시간대도 검증해야 공정하지."],
        "counter_soft": ["{target}의 말이라… 그 출처부터 다시 봐야겠군."],
        "partial_admit": ["…정정할게. {room} 앞까지는 갔어. 안으로 들어가진 않았어. {pos|ira}고 한 건 내 실수야."],
        "vouch_hold": ["{target|wa} 같이 있었어. 그 값은 고정이야."],
        "already_told": ["이미 말했어. 반복해도 답은 같아."],
        "deflect": ["그건 이번 사건과 무관한 변수야. 넘어가자.", "…나중에 설명하지."],
        "explain_with": ["난 {pos}에 있었어. {mate}한테 확인해. 교차 검증하면 끝나.", "{mates|wa} 있었어. {source|i} 본 건 다른 사람이야."],
        "explain_alone": ["혼자였던 건 사실이야. 그래도 {room}엔 안 갔어."],
        "misremember": ["잠깐. 내가 순서를 뒤집어 기억했어. {pos|ieot}어. 오류는 오류로 인정할게."],
        "confess": ["…정정하지. 난 그때 {pos}에 있었어. 이유가 있어."],
        "confess_pressed": ["좋아. 말하지. {pos}에 있었어."],
        "incident_note": ["{time}, {room}. 걸린 건 {stake}. 우연으로 설명할 수 있는 확률은 0에 가까워."],
        "recovered_record": ["{from}의 기록은 내 쪽 백업에 복사돼 있었어. 어제 그 시간대 원본이야."],
        "morning_mourn": ["{victim}의 신호가 끊겼어. …계산에 없던 결과야."],
        "morning_resolve": ["변수가 하나 줄었어. 남은 변수로 다시 계산하자."],
        "morning_relief": ["{target|i} 무사해. 차폐가 작동했어."],
        "morning_attacked_meaning": ["{target|eul} 노렸다는 건 {target}의 정보가 누군가에게 위협이었다는 뜻이야."],
        "morning_quiet": ["밤 동안 이상 없음. 그 자체로 하나의 데이터야."],
        "morning_after_vote": ["{target}의 포드는 정상이야. 우리 판단이 맞았는지는 아직 검증 전이고."],
        "after_isolation": ["한 명을 빼면 조건이 바뀌어. 그 뒤의 변화도 증거로 남겨야 해."],
        "last_plea": ["나를 빼고도 사건이 계속되면, 그게 답이야.", "투표는 확률이야. 확률로 사람을 재우는 거지. 알고 해.", "내 조건은 다 말했어. 남은 건 너희 계산이야."],
        "m_record": ["로그 하나 공개하지. {record}"],
        "m_group_answer": ["{members} 중에 나도 있어. 그 조건만으로는 부족해."],
        "m_caution": ["{target|eul} 지목하기엔 변수가 아직 남았어. 서두르지 마."],
        "m_saw": ["내가 봤어. {time}쯤 {target|i} {room} 쪽으로 갔어."],
        "m_saw_group": ["{time}쯤 {phrase} {room} 쪽으로 갔어. 해당하는 건 {members}."],
        "m_defend_self": ["난 {pos}에 있었어. {mates|rang} 같이. {target}, 근거를 대."],
        "m_vouch": ["{target|eun} 그때 나랑 {pos}에 있었어. 그건 확실해."],
        "m_catch_lie": ["{a}의 진술과 {b}의 진술은 동시에 참일 수 없어. 둘 중 하나는 틀렸어."],
        "m_benign_callout": ["{target}, {mate}의 진술에 따르면 넌 거기 있었어. {pos|eun} 뭐지?"],
        "m_deflect": ["그건 이번 사건과 무관해. 넘어가지."],
        "m_confess_public": ["…정정하지. 그때 {pos}에 있었어."],
        "m_callback": ["{target}, {when} {old|ieot}어. 지금은 {new}. 값이 바뀌었어."],
        "m_deny": ["그건 사실이 아니야.", "해석이 틀렸어."],
        "m_yesterday": ["어제 {target|eul} 뺐는데 사건이 이어졌어. 가정 하나가 틀렸을 수도 있어."],
        "m_forward": ["틀린 가정은 버리면 돼. 다시 계산하자."],
        "m_accuse": ["{target}. 근거는 {reason}. 지금 데이터로는 네가 가장 설명이 안 돼."],
        "m_agree": ["동의해. {target} 쪽 변수가 가장 커."],
        "m_excuse_remote": ["그 인증은 원격 동기화 과정일 수 있어. 난 {room}에 없었어."],
        "m_excuse_auto": ["자동 스케줄러가 돌았을 거야."],
        "m_excuse_card": ["토큰 복제 가능성을 배제할 수 없어."],
        "m_rebut": ["그 설명은 구조적으로 불가능해. {fact}"],
        "m_demand": ["{target}, 그럼 다른 설명을 내놔."],
        "m_shift": ["…입력이 바뀌었군. {reason}. 이제 {target|i} 가장 커."],
        "m_confirm": ["맞아. 내가 확인한 거야."],
        "m_retreat": ["…관측 오류였을 수 있어. {target|ira}고 단정한 건 철회하지."],
        "m_thanks": ["…고맙군."]
    },
    "noa": {
        "open_with": ["{time}. {pos}. {mates|wa} 같이요. 서로 시간 확인했어요.",
            "{pos}에 있었어요. {mates}도요. 제 메모에 적혀 있어요.", "{mates|wa} {pos}에 있었어요. {time}. 시계도 같이 봤어요."],
        "open_alone": ["{time}. {pos}에 혼자 있었어요. 기록 정리 중이었어요.",
            "혼자요. {pos}. 누가 지나갔다면 발소리는 적었을 거예요. 없었어요.", "{pos}에 있었어요. 혼자. {time}. 메모엔 그렇게 적혀 있어요.", "혼자였어요. {pos}에서 어제 메모를 옮겨 적고 있었어요.", "{time}, {pos}. 혼자요. 확인해 줄 건… 제 메모뿐이네요."],
        "hint_record": ["단말 접속 기록이 있어요. 그 시간 누가 어디서 로그인했는지."],
        "hint_saw": ["…적어 둔 게 하나 있어요. 사람이에요."],
        "saw_specific": ["{time}. {target|i} {room} 쪽으로 갔어요. 적어 뒀어요.",
            "제 메모예요. ‘{time}, {target}, {room} 방향.’"],
        "saw_group": ["{time}. {phrase} {room} 쪽으로 갔어요. 이름은 안 적었어요. 확인 안 된 건 안 적어요."],
        "heard": ["{via|i} 누군가를 봤다고 했어요. 전언이에요. 원문은 {via}한테 들어야 해요."],
        "saw_at": ["{time}. {target|eun} {room}에 있었어요. 제가 봤어요."],
        "record_open": ["단말 접속 기록이에요. 그대로 읽을게요."],
        "record_meaning_specific": ["{target}의 개인 단말이에요. 로컬 접속이고요."],
        "record_meaning_group": ["특정 단말은 아니에요. {members} 중 한 명이에요."],
        "record_support": ["{target}. 그 시간 {room}에 로그인돼 있었어요."],
        "inference": ["삭제는 로컬 단말에서 됐어요. 원격 흔적이 없어요."],
        "saw_none": ["아무도요.", "못 봤어요. 발소리도 없었어요."],
        "yesterday_same": ["어제와 같아요. {pos}."],
        "yesterday_changed": ["어제는 {pos|ieyo}. …{old|ira}고 했나요? 제 메모가 틀렸을 수도 있어요."],
        "opinion": ["{target}. 이유는 {reason}. 그 이상은 아직 몰라요.", "지금은 {target|ieyo}. {reason|i} 걸려요."],
        "opinion_none": ["아직 모르겠어요. 확인된 게 부족해요."],
        "reassure": ["…고마워요. 적어 둘게요."],
        "pressure_null": ["압박한다고 문장이 바뀌진 않아요."],
        "pressure_crew": ["제가 한 말은 제 메모와 같아요. 몇 번을 물어도요."],
        "deny": ["아니에요. {room}에 안 갔어요.", "그건 제가 아니에요."],
        "excuse_remote": ["단말 동기화 기록일 수 있어요. 원격으로 찍히기도 해요."],
        "excuse_auto": ["자동 저장 기록이에요. 사람이 한 게 아닐 수도 있어요."],
        "excuse_card": ["제 카드는 책상 위에 둘 때가 있어요. 누가 썼을 수도요."],
        "counter": ["{target|i} 그렇게 말했어요? {target}의 그 시간 진술부터 다시 읽어 봐요."],
        "counter_soft": ["{target}의 말은 적어 둘게요. 출처로요."],
        "partial_admit": ["…정정할게요. {room} 앞까지 갔어요. 안에는 안 들어갔어요. {pos|ira}고 한 건 틀렸어요."],
        "vouch_hold": ["{target|wa} 같이 있었어요. 메모에 있어요."],
        "already_told": ["이미 말했어요. 같은 문장이에요."],
        "deflect": ["그건 나중에요.", "…확인 전에는 말하고 싶지 않아요."],
        "explain_with": ["{pos}에 있었어요. {mate}한테 확인하세요.", "{mates|wa} 있었어요. {source}의 말은 제 기록과 달라요."],
        "explain_alone": ["혼자였어요. 그래도 {room}엔 안 갔어요."],
        "misremember": ["…제가 착각했어요. {pos|ieot}어요. 메모 순서가 뒤집혔어요."],
        "confess": ["…정정할게요. {pos}에 있었어요. 이유가 있어요."],
        "confess_pressed": ["네. 바로잡을게요. {pos|ieot}어요."],
        "incident_note": ["{time}, {room}. 대상은 {stake}. 기록부터 남길게요."],
        "recovered_record": ["{from}의 기록, 제 백업에 남아 있었어요. 어제 그 시간 거예요."],
        "morning_mourn": ["{victim}의 마지막 기록은 어제 저녁이에요. 그 뒤로 없어요."],
        "morning_resolve": ["기록할게요. 그리고 찾을게요."],
        "morning_relief": ["{target|i} 무사해요. 적어 둘게요."],
        "morning_attacked_meaning": ["{target|eul} 노렸다는 것도 기록이에요. 이유가 있을 거예요."],
        "morning_quiet": ["밤사이 기록 없음. …이것도 적어 둘게요."],
        "morning_after_vote": ["격리 결정과 사실 확인은 다른 항목으로 기록했어요. {target}의 칸은 아직 비어 있어요."],
        "after_isolation": ["격리 결정과 사실 확인은 다른 항목으로 기록할게요."],
        "last_plea": ["제 메모는 두고 갈게요. 읽어 주세요.", "제가 한 말은 전부 적혀 있어요. 바뀐 문장이 있으면 찾아 보세요.", "기록은 저보다 정확해요. 저를 믿지 말고 기록을 믿어요."],
        "m_record": ["제 기록이에요. 그대로 읽을게요. {record}"],
        "m_group_answer": ["{members} 중에 저도 있어요. 저는 제 자리에 있었어요."],
        "m_caution": ["{target}에 대해 확인된 건 아직 하나예요. 결론은 이르다고 적을게요."],
        "m_saw": ["제 메모예요. {time}, {target}, {room} 방향."],
        "m_saw_group": ["{time}. {phrase} {room} 쪽으로 갔어요. 해당하는 건 {members|ieyo}."],
        "m_defend_self": ["저는 {pos}에 있었어요. {mates|wa} 같이요. {target}, 근거가 뭐예요?"],
        "m_vouch": ["{target}. 그 시간 저랑 {pos}에 있었어요. 적어 뒀어요."],
        "m_catch_lie": ["{a}의 문장과 {b}의 문장은 같이 맞을 수 없어요."],
        "m_benign_callout": ["{target}. {mate}의 진술에선 당신이 같이 있었어요. {pos|eun} 달라요."],
        "m_deflect": ["…나중에요."],
        "m_confess_public": ["정정할게요. 그 시간 {pos}에 있었어요."],
        "m_callback": ["{target}. {when} {old|ira}고 했어요. 지금은 {new|ieyo}."],
        "m_deny": ["아니에요.", "제 문장은 그대로예요."],
        "m_yesterday": ["어제 {target|eul} 격리했어요. 오늘도 사건이 있었어요. 두 문장을 같이 적어 둘게요."],
        "m_forward": ["그럼 오늘 기록을 더 정확히 남겨요."],
        "m_accuse": ["{target}. 이유는 {reason}. 그게 제 판단이에요."],
        "m_agree": ["저도 {target|iyo}."],
        "m_excuse_remote": ["원격 동기화 기록일 수 있어요. 저는 {room}에 없었어요."],
        "m_excuse_auto": ["자동 저장이에요."],
        "m_excuse_card": ["제 카드를 누가 썼을 수도 있어요."],
        "m_rebut": ["그건 안 돼요. {fact}"],
        "m_demand": ["{target}. 다시 설명해 주세요. 적을게요."],
        "m_shift": ["…수정할게요. {reason}. 지금은 {target|ieyo}."],
        "m_confirm": ["맞아요. 제가 말한 거예요."],
        "m_retreat": ["…제 메모가 틀렸을 수 있어요. {target|ira}고 쓴 건 지울게요."],
        "m_thanks": ["…고마워요."]
    },
    "sena": {
        "open_with": ["{time}엔 {pos}. {mates|rang} 같이 있었어. 보안 동선대로 움직였고.",
            "{pos}에 있었어. {mates}도 같이. 확인하고 싶으면 출입 기록 까 봐.", "{mates|rang} 같이 있었어. {pos}. 서로 눈에 보이는 데 있었어."],
        "open_alone": ["{pos}에 혼자 있었어. 순찰 중이었지. 증인? 순찰은 원래 혼자 해.",
            "{time}? {pos}. 혼자. 그게 문제면 문제라고 해.", "{pos}. 혼자. 교대 시간 기다리면서 문 앞을 지키고 있었어.", "{time}엔 {pos}에 있었어. 혼자. 그 시간에 누가 움직였는지 나도 알고 싶어.", "혼자였어. {pos}. 증인 없는 건 내가 제일 싫어하는 조건인데, 사실이야."],
        "hint_record": ["출입 인증 기록 봐야 해. 그 시간 누가 어느 문을 열었는지 다 남아."],
        "hint_saw": ["순찰 돌다가 누구 하나 봤어. 말할까 말까 했는데."],
        "saw_specific": ["{time}쯤 {target|i} {room} 쪽으로 가는 걸 봤어. 순찰 동선상 거기 있을 이유가 없어.",
            "{target}. {time}. {room} 앞. 내가 똑똑히 봤어."],
        "saw_group": ["{time}쯤 {phrase} {room} 쪽으로 갔어. 거리가 있어서 얼굴은 못 봤어."],
        "heard": ["{via|i} 누굴 봤대. 나한테 말한 건데, 본인한테 다시 들어."],
        "saw_at": ["{time}쯤 {target|eun} {room}에 있었어. 순찰하면서 봤어."],
        "record_open": ["출입 인증 기록이야. 문은 거짓말 안 해."],
        "record_meaning_specific": ["{target}의 카드로 열렸어. 카드 도난 신고는 없었어."],
        "record_meaning_group": ["권한 등급까지만 찍혔어. {members} 중 하나야."],
        "record_support": ["{target|eun} 그때 {room}에 있었어. 출입 기록이 증명해."],
        "inference": ["그 문은 안쪽 패널에서 손으로 풀어야 열려. 카드만으론 안 돼."],
        "saw_none": ["못 봤어. 내 동선엔 아무도 없었어.", "아무도. 복도는 비어 있었어."],
        "yesterday_same": ["어제도 {pos}. 똑같아."],
        "yesterday_changed": ["어제는 {pos|ieot}어. …{old|ira}고 했나? 순찰 경로가 헷갈렸나 봐."],
        "opinion": ["{target}. {reason}, 그게 걸려. 난 돌려 말 안 해.", "내 눈엔 {target}. {reason|i} 설명이 안 돼."],
        "opinion_none": ["아직 없어. 근거 없이 찍는 건 보안이 아니라 도박이야."],
        "reassure": ["…고마워. 나 원래 이런 말 잘 안 하는데."],
        "pressure_null": ["지금 나한테 협박하는 거야? 해 봐."],
        "pressure_crew": ["몰아세워도 난 안 흔들려. 본 대로 말했어."],
        "deny": ["난 {room}에 안 갔어. 끝.", "아니야. 나 아니야."],
        "excuse_remote": ["그 인증? 원격 점검이야. 보안 시스템이 가끔 그래."],
        "excuse_auto": ["자동 잠금 해제 주기에 걸린 거야."],
        "excuse_card": ["내 카드 복제됐을 수도 있어. 보안 책임자 카드라 노리는 사람 많아."],
        "counter": ["{target|i} 그랬어? {target} 동선부터 까 봐. 나보다 더 설명 못 할걸."],
        "counter_soft": ["{target|i} 그렇게 말했다고? 이유가 궁금하네."],
        "partial_admit": ["…좋아. {room} 앞까지는 갔어. 안에는 안 들어갔어. {pos|ira}고 한 건 거짓말이었어. 미안."],
        "vouch_hold": ["{target|rang} 같이 있었다니까. 내 말 못 믿어?"],
        "already_told": ["말했잖아. 그게 다야."],
        "deflect": ["그건 나중에. 지금 그 얘기 할 때 아니야.", "…건드리지 마, 그건."],
        "explain_with": ["난 {pos}에 있었어. {mate}한테 물어봐.", "{mates|rang} 같이 있었어. {source|i} 잘못 본 거야."],
        "explain_alone": ["혼자였던 건 맞아. 순찰이니까. 그래도 {room}엔 안 갔어."],
        "misremember": ["아, 잠깐. 순찰 경로를 거꾸로 기억했어. {pos|ieot}어."],
        "confess": ["…알았어. 사실 {pos}에 있었어. 이유가 있어."],
        "confess_pressed": ["그래, 말할게. {pos}에 있었어."],
        "incident_note": ["{time}, {room}. 노린 건 {stake}. 이건 보안 사고야. 누군가 일부러 한 거야."],
        "recovered_record": ["{from}의 기록, 보안 백업에 남아 있었어. 어제 그 시간 거야."],
        "morning_mourn": ["{victim}… 내가 순찰을 한 번 더 돌았어야 했어."],
        "morning_resolve": ["슬퍼하는 건 나중에. 오늘 안에 찾는다."],
        "morning_relief": ["{target|i} 무사해. …차폐가 버텼어."],
        "morning_attacked_meaning": ["{target|eul} 노렸다는 건, {target|i} 누군가한테 위협이었다는 뜻이야."],
        "morning_quiet": ["밤새 이상 없음. 그래도 경계는 안 풀어."],
        "morning_after_vote": ["{target}의 포드는 잠겨 있어. 판단이 맞았는지는… 오늘 보면 알겠지."],
        "after_isolation": ["포드는 잠겼어. 나머지 출입은 다시 확인한다."],
        "last_plea": ["나 보내고도 일 생기면, 그때는 진짜 조심해.", "난 도망 안 가. 문 앞에서 기다릴게.", "틀렸으면 그 대가는 오늘 밤에 치르게 될 거야. 그것만 기억해."],
        "m_record": ["문은 거짓말 안 해. 공개한다. {record}"],
        "m_group_answer": ["{members}? 나도 걸리네. 난 순찰 중이었어."],
        "m_caution": ["{target|eul} 몰기 전에 근거부터 확인해. 성급한 격리는 보안이 아니야."],
        "m_saw": ["{time}쯤 {target|i} {room} 쪽으로 가는 거, 똑똑히 봤어."],
        "m_saw_group": ["내가 봤어. {time}쯤 {phrase} {room} 쪽으로 가더라. 얼굴은 못 봤고, {members} 중 하나야."],
        "m_defend_self": ["난 {pos}에 있었어. {mates|rang} 같이. {target}, 근거 있어?"],
        "m_vouch": ["{target|rang} 나 그때 {pos}에 있었어. 내가 보증해."],
        "m_catch_lie": ["{a|rang} {b} 말이 안 맞아. 누가 거짓말하는 거야?"],
        "m_benign_callout": ["{target}. {mate|i} 너랑 같이 있었대. 근데 넌 {pos|ira}며. 설명해."],
        "m_deflect": ["그건 사건이랑 상관없어."],
        "m_confess_public": ["…말할게. 그때 {pos}에 있었어."],
        "m_callback": ["{target}, {when} {old|ira}며. 지금은 {new}? 말 바꾸지 마."],
        "m_deny": ["아니야.", "그런 말 한 적 없어."],
        "m_yesterday": ["어제 {target} 보냈는데 오늘 또 터졌어. 우리 판단이 틀렸을 수도 있어."],
        "m_forward": ["틀렸으면 오늘 제대로 하면 돼. 규정대로 가자."],
        "m_accuse": ["{target}. {reason}. 난 네가 제일 위험해 보여."],
        "m_agree": ["동의해. {target}."],
        "m_excuse_remote": ["그 인증? 원격 점검이야. 나 {room} 근처에도 안 갔어."],
        "m_excuse_auto": ["자동 해제 주기야."],
        "m_excuse_card": ["내 카드 복제됐을 수 있어."],
        "m_rebut": ["그건 안 돼. {fact}"],
        "m_demand": ["{target}, 설명해. 지금 당장."],
        "m_shift": ["…그럼 얘기가 달라지네. {reason}. 이제 {target}."],
        "m_confirm": ["맞아. 내가 말한 거야."],
        "m_retreat": ["…내가 잘못 봤을 수도 있어. {target|ira}고 한 건 취소할게."],
        "m_thanks": ["…고마워. 신세 졌네."]
    },
    "vale": {
        "open_with": ["{time}쯤이면 {pos}에 있었어요. {mates|wa} 같이요. 그 시간 신호가 조용했던 것도 기억해요.",
            "{pos|iyo}. {mates}도 있었어요. 헤드셋을 벗고 있었으니까, 대화도 했어요.", "{mates|wa} 같이 {pos}에 있었어요. 조용히, 옆에서요."],
        "open_alone": ["{pos}에 혼자 있었어요. 채널 잡음을 듣고 있었어요.",
            "혼자였어요. {pos}. 누가 지나갔다면 발소리보다 문 여는 소리를 먼저 들었을 거예요.", "{pos|iyo}. 혼자… 한쪽 이어폰만 끼고 있었어요.", "{time}쯤엔 {pos}에 있었어요. 혼자서요. 사람 목소리는 못 들었어요.", "혼자였어요. {pos}. 조용한 게 좋아서 거기 있었어요."],
        "hint_record": ["통신 채널 접속 기록이 있어요. 누가 어느 단말로 채널을 열었는지 남아요."],
        "hint_saw": ["…들은 게 하나 있어요. 본 것에 가까운 소리요."],
        "saw_specific": ["{time}쯤 {target|i} {room} 쪽으로 가는 걸 봤어요. 발소리 간격이 급했어요.",
            "{target|ieot}어요. {time}쯤, {room} 방향이요."],
        "saw_group": ["{time}쯤 {phrase} {room} 쪽으로 갔어요. 얼굴은 못 봤어요."],
        "heard": ["{via|i} 누군가를 봤다고 했어요. 전해 들은 말은 한 번 더 걸러야 해요. {via}한테 직접 들으세요."],
        "saw_at": ["{time}쯤 {target|eun} {room}에 있었어요. 목소리를 들었어요."],
        "record_open": ["통신 채널 접속 기록이에요. 발신 단말이 남아 있어요."],
        "record_meaning_specific": ["{target}의 단말이에요. 경로상 중계를 거치지 않았어요. 현장에서 연 거예요."],
        "record_meaning_group": ["단말 종류까지만 보여요. {members} 중 한 명이에요."],
        "record_support": ["{target|eun} 그때 {room}에서 채널에 접속해 있었어요."],
        "inference": ["그 승인은 중계 단말 앞에서만 돼요. 원격 경로는 막혀 있어요."],
        "saw_none": ["아무도요. 제가 듣던 건 사람 소리가 아니었어요.", "못 봤어요. 조용했어요."],
        "yesterday_same": ["…어제랑 같아요. {pos}에 있었어요."],
        "yesterday_changed": ["어제는 {pos|ieot}어요. {old|ira}고 했나요? …같은 구간을 두 번 들은 것 같네요."],
        "opinion": ["{target|ieyo}. {reason|i} 걸려요. 출처가 확실한 말만 믿으려고요.", "지금은 {target} 쪽이에요. 근거는 {reason}."],
        "opinion_none": ["아직 신호가 약해요. 이름을 말할 수준이 아니에요."],
        "reassure": ["…고마워요. 조용히 말할 수 있어서 좋네요."],
        "pressure_null": ["소리를 높인다고 잡음이 사라지진 않아요."],
        "pressure_crew": ["제가 들은 건 그대로예요. 몇 번을 물어도요."],
        "deny": ["저는 {room}에 가지 않았어요.", "그건 제가 아니에요."],
        "excuse_remote": ["그 접속은 중계 루프일 수 있어요. 제 단말이 경로에 찍혔을 뿐이에요."],
        "excuse_auto": ["자동 수신 승인이었을 거예요. 가끔 그렇게 돼요."],
        "excuse_card": ["제 인증을 누가 빌렸을 수도 있어요."],
        "counter": ["{target|i} 그렇게 말했나요? {target}의 말이 어디서 왔는지부터 확인해야 해요."],
        "counter_soft": ["{target}의 말… 출처가 궁금하네요."],
        "partial_admit": ["…맞아요. {room} 앞까지는 갔어요. 안에는 안 들어갔어요. {pos|ira}고 한 건… 틀렸어요."],
        "vouch_hold": ["{target|wa} 같이 있었어요. 그건 분명해요."],
        "already_told": ["이미 말했어요."],
        "deflect": ["그건… 아직 말할 준비가 안 됐어요.", "나중에요. 부탁이에요."],
        "explain_with": ["저는 {pos}에 있었어요. {mate}한테 물어보세요.", "{mates|wa} 있었어요. {source}의 말은 제가 들은 것과 달라요."],
        "explain_alone": ["혼자였어요. 그래도 {room}엔 가지 않았어요."],
        "misremember": ["아… 제가 구간을 착각했어요. {pos|ieot}어요."],
        "confess": ["…말할게요. 사실 {pos}에 있었어요."],
        "confess_pressed": ["…맞아요. {pos|ieot}어요."],
        "incident_note": ["{time}, {room}. 건드려진 건 {stake}. 신호가 먼저 바뀐 지점부터 볼게요."],
        "recovered_record": ["{from}의 기록이 중계 캐시에 남아 있었어요. 어제 그 시간 거예요."],
        "morning_mourn": ["{victim}의 채널이 조용해요. …이런 조용함은 싫어요."],
        "morning_resolve": ["누가 그랬는지, 소리를 따라가 볼게요."],
        "morning_relief": ["{target|i} 무사해요. 차폐 경보가 울렸어요."],
        "morning_attacked_meaning": ["{target|eul} 노렸다면, {target}의 말이 누군가에게는 잡음이 아니었던 거예요."],
        "morning_quiet": ["밤새 채널이 조용했어요. 너무 조용했어요."],
        "morning_after_vote": ["{target}의 포드는 신호가 안정적이에요. 우리가 맞았는지는 아직 몰라요."],
        "after_isolation": ["이제 신호가 달라지는지 들어 볼게요."],
        "last_plea": ["제 녹음은 남겨 둘게요. 끝까지 들어 주세요.", "…제 목소리가 이상하게 들린다면, 그건 저도 무서워서예요.", "말을 아낀 건 맞아요. 숨긴 건 아니에요."],
        "m_record": ["제 채널 기록이에요. 공유할게요. {record}"],
        "m_group_answer": ["{members} 중에 저도 있어요. 저는 채널을 듣고 있었어요."],
        "m_caution": ["{target}에 대한 말은 아직 출처가 하나예요. 한 번 더 걸러요."],
        "m_saw": ["말할게요. {time}쯤 {target|i} {room} 쪽으로 갔어요."],
        "m_saw_group": ["{time}쯤 {phrase} {room} 쪽으로 갔어요. 해당하는 건 {members|ieyo}."],
        "m_defend_self": ["저는 {pos}에 있었어요. {mates|wa} 같이요. {target}, 그 말은 어디서 들은 거예요?"],
        "m_vouch": ["{target|eun} 그 시간 저랑 {pos}에 있었어요."],
        "m_catch_lie": ["{a}의 말과 {b}의 말이 같은 시각에 겹쳐요. 둘 다 맞을 수는 없어요."],
        "m_benign_callout": ["{target}, {mate}의 말로는 당신이 같이 있었어요. {pos|eun} 달라요."],
        "m_deflect": ["…그건 나중에요."],
        "m_confess_public": ["…말할게요. 그 시간 {pos}에 있었어요."],
        "m_callback": ["{target}, {when} {old|ieot}어요. 지금은 {new}. 같은 목소리로 다른 말을 하네요."],
        "m_deny": ["그렇지 않아요.", "제 말은 바뀌지 않았어요."],
        "m_yesterday": ["어제 {target|eul} 보냈는데… 신호는 멈추지 않았어요."],
        "m_forward": ["그럼 오늘은 더 조용히, 더 정확히 들어요."],
        "m_accuse": ["{target}. 근거는 {reason}. 제가 들은 걸 종합하면 그래요."],
        "m_agree": ["저도 {target} 쪽이에요."],
        "m_excuse_remote": ["그 접속은 중계 루프일 수 있어요. 저는 {room}에 없었어요."],
        "m_excuse_auto": ["자동 수신 승인이에요."],
        "m_excuse_card": ["누가 제 인증을 빌렸을 수 있어요."],
        "m_rebut": ["그 설명은 안 맞아요. {fact}"],
        "m_demand": ["{target}, 다시 말해 줄래요? 이번엔 정확하게."],
        "m_shift": ["…다시 들어 보니, {reason}. 지금은 {target|ieyo}."],
        "m_confirm": ["네. 제가 말한 거예요."],
        "m_retreat": ["…제가 잘못 들었을 수도 있어요. {target|ira}고 한 건 거둘게요."],
        "m_thanks": ["…고마워요."]
    },
    "eli": {
        "open_with": ["{time}. {pos}. {mates|rang} 같이.", "{pos}에 있었어. {mates}도. 동선 겹치는 거 확인해 봐.", "{mates|rang} {pos}. {time}. 같이 있었어."],
        "open_alone": ["{pos}. 혼자.", "{time}엔 {pos}에 혼자 있었어. 좌표 맞추고 있었어.", "혼자. {pos}. {time}. 시계 확인했어.", "{pos}에 있었어. 혼자. 거기서 다음 동선 계산하고 있었어.", "{time}? {pos}. 혼자였어. 확인해 줄 사람은 없어."],
        "hint_record": ["통로 이동 센서 기록이 있어. 누가 어느 방향으로 갔는지 남아."],
        "hint_saw": ["지나가는 걸 하나 봤어. 방향이 이상했어."],
        "saw_specific": ["{time}. {target}. {room} 방향.", "{target|i} {room} 쪽으로 갔어. {time}쯤. 걸음이 빨랐어."],
        "saw_group": ["{time}쯤 {phrase} {room} 쪽으로 갔어. 얼굴은 못 봤어."],
        "heard": ["{via|i} 누굴 봤대. 난 못 봤어. {via}한테 물어."],
        "saw_at": ["{time}. {target|eun} {room}에 있었어. 확실해."],
        "record_open": ["통로 이동 센서야. 방향과 시각이 같이 남아."],
        "record_meaning_specific": ["{target}의 태그가 그 방향으로 이동했어."],
        "record_meaning_group": ["태그 종류까지만. {members} 중 하나야."],
        "record_support": ["{target|eun} 그때 {room}에 있었어. 센서상으로."],
        "inference": ["항법 구간은 항법실 콘솔에서만 지워져. 원격 편집은 잠겨 있어."],
        "saw_none": ["못 봤어.", "아무도. 그 구간은 비어 있었어."],
        "yesterday_same": ["어제도 {pos}."],
        "yesterday_changed": ["어제는 {pos}. …{old|ira}고 했나. 좌표를 잘못 말했네."],
        "opinion": ["{target}. {reason}.", "지금은 {target}. {reason|i} 안 맞아."],
        "opinion_none": ["아직. 좌표가 모자라."],
        "reassure": ["…고마워. 말은 잘 못 해도, 알아들었어."],
        "pressure_null": ["밀어붙인다고 위치가 바뀌진 않아."],
        "pressure_crew": ["내 위치는 내가 말한 그대로야."],
        "deny": ["{room}엔 안 갔어.", "아니야."],
        "excuse_remote": ["원격 동기화야. 내가 거기 있던 게 아니야."],
        "excuse_auto": ["자동 보정이 돌았어. 사람 손이 아니야."],
        "excuse_card": ["내 태그를 누가 빼 갔을 수도 있어."],
        "counter": ["{target|i} 그랬어? {target}의 그 시각 위치부터 맞춰 봐."],
        "counter_soft": ["{target}. 그 말 위치가 이상해."],
        "partial_admit": ["…{room} 앞까진 갔어. 안에는 안 들어갔어. {pos|ira}고 한 건 틀렸어."],
        "vouch_hold": ["{target|rang} 같이 있었어. 위치는 안 바뀌어."],
        "already_told": ["이미 말했어."],
        "deflect": ["그건 나중에.", "…지금은 아니야."],
        "explain_with": ["{pos}에 있었어. {mate}한테 확인해.", "{mates|rang} 있었어. {source|i} 본 건 다른 사람이야."],
        "explain_alone": ["혼자였어. 그래도 {room}엔 안 갔어."],
        "misremember": ["…좌표를 거꾸로 기억했어. {pos|ieot}어."],
        "confess": ["…정정할게. {pos}에 있었어."],
        "confess_pressed": ["알았어. {pos}."],
        "incident_note": ["{time}, {room}. 표적은 {stake}. 위치부터 맞추자."],
        "recovered_record": ["{from}의 기록, 항법 백업에 남아 있었어. 어제 그 시각."],
        "morning_mourn": ["{victim}의 좌표가 멈췄어."],
        "morning_resolve": ["남은 사람 위치부터 다시 맞춘다."],
        "morning_relief": ["{target|i} 무사해."],
        "morning_attacked_meaning": ["{target|eul} 노렸다는 건, {target}의 위치에 뭔가 있었다는 거야."],
        "morning_quiet": ["밤새 이동 없음."],
        "morning_after_vote": ["{target}의 포드 좌표는 그대로야. 맞았는지는 아직 몰라."],
        "after_isolation": ["사람 하나를 뺐다고 항로까지 맞아지는 건 아니야."],
        "last_plea": ["나 없이도 위치는 맞춰.", "동선 다시 그려 봐. 내가 거기 있을 수 있었는지.", "틀리면 시계를 봐. 시간은 거짓말 안 해."],
        "m_record": ["내 기록이야. {record}"],
        "m_group_answer": ["{members}. 나도 걸려. 난 항법실에 있었어."],
        "m_caution": ["{target}. 위치가 확인 안 됐어. 아직 이르다."],
        "m_saw": ["봤어. {time}. {target}. {room} 방향."],
        "m_saw_group": ["{time}쯤 {phrase} {room} 쪽으로 갔어. {members} 중 하나."],
        "m_defend_self": ["난 {pos}에 있었어. {mates|rang} 같이. {target}, 좌표 대."],
        "m_vouch": ["{target|rang} 그때 {pos}에 있었어."],
        "m_catch_lie": ["{a|rang} {b}. 같은 시각에 두 위치일 수 없어."],
        "m_benign_callout": ["{target}. {mate|i} 너랑 같이 있었대. {pos|eun} 아니야."],
        "m_deflect": ["그건 상관없어."],
        "m_confess_public": ["정정할게. 그때 {pos}에 있었어."],
        "m_callback": ["{target}. {when} {old}. 지금은 {new}. 위치가 바뀌었어."],
        "m_deny": ["아니야.", "그 위치는 틀렸어."],
        "m_yesterday": ["어제 {target} 보냈어. 사건은 이어졌어. 계산을 다시 해야 해."],
        "m_forward": ["그럼 오늘 좌표를 더 정확히 맞추자."],
        "m_accuse": ["{target}. {reason}. 위치가 안 맞아."],
        "m_agree": ["{target}. 동의해."],
        "m_excuse_remote": ["원격 동기화야. 난 {room}에 없었어."],
        "m_excuse_auto": ["자동 보정이야."],
        "m_excuse_card": ["태그를 누가 빼 갔을 수 있어."],
        "m_rebut": ["안 돼. {fact}"],
        "m_demand": ["{target}. 다시 말해. 위치로."],
        "m_shift": ["…다시 맞춰 보니 {target}. {reason}."],
        "m_confirm": ["맞아. 내가 말했어."],
        "m_retreat": ["…잘못 봤을 수 있어. {target|eun} 취소."],
        "m_thanks": ["…고마워."]
    },
    "lyra": {
        "open_with": ["{time}쯤이요? {pos}에 있었어요. {mates|wa} 같이요. 물 주는 시간이라 기억해요.",
            "{pos|iyo}. {mates}도 있었어요. 같이 있으면 시간이 빨리 가잖아요.", "{mates|wa} {pos}에 있었어요. 같이 이야기하고 있었어요."],
        "open_alone": ["{pos}에 혼자 있었어요. 시든 잎을 골라내고 있었어요.",
            "혼자였어요. {pos}. 식물들은 증언을 못 해 주니까 아쉽네요.", "{pos}에 있었어요. 혼자서요. 새 잎이 났나 보러 갔었어요.", "{time}쯤엔 {pos}. 혼자였어요. 조용해서 좋았는데, 지금은 그게 불리하네요.", "혼자요. {pos}에서 물 주는 순서를 다시 정하고 있었어요."],
        "hint_record": ["구역 대기 센서가 있어요. 사람이 있으면 공기가 달라져요. 그 기록을 볼 수 있어요."],
        "hint_saw": ["아, 누굴 보긴 했어요. 말해도 될지 모르겠네요."],
        "saw_specific": ["{time}쯤 {target|i} {room} 쪽으로 가는 걸 봤어요. 인사하려다 말았어요.",
            "{target|ieot}어요. {time}쯤 {room} 쪽이요. 걸음이 평소보다 빨랐어요."],
        "saw_group": ["{time}쯤 {phrase} {room} 쪽으로 갔어요. 뒷모습만 봤어요."],
        "heard": ["{via|i} 누굴 봤다고 그랬어요. 떨리는 목소리였어요. {via}한테 직접 들어 봐요."],
        "saw_at": ["{time}쯤 {target|eun} {room}에 있었어요. 제가 봤어요."],
        "record_open": ["구역 대기 센서예요. 숨 쉬는 사람이 있으면 이산화탄소가 올라가요."],
        "record_meaning_specific": ["{target}의 생체 태그가 같이 잡혔어요. 그 시간 거기 있었어요."],
        "record_meaning_group": ["태그 종류까지만 보여요. {members} 중 한 명이에요."],
        "record_support": ["{target|eun} 그 시간 {room}에 있었어요. 공기가 그렇게 말해요."],
        "inference": ["그 분류는 생태 단말에 직접 들어가야 바뀌어요. 자동으로는 안 돼요."],
        "saw_none": ["아무도 못 봤어요. 식물만 보고 있었어요.", "아무도 못 봤어요. 잎 흔들리는 소리밖에 없었어요."],
        "yesterday_same": ["어제와 같아요. {pos}에 있었어요."],
        "yesterday_changed": ["어제는… {pos|ieot}어요. {old|ira}고 했나요? 제가 헷갈렸나 봐요."],
        "opinion": ["{target|ieyo}. {reason|i} 마음에 걸려요. 그래도 틀렸으면 좋겠어요.", "지금은 {target} 쪽이에요. {reason|i} 신경 쓰여요."],
        "opinion_none": ["아직 모르겠어요. 섣불리 이름 대고 싶지 않아요."],
        "reassure": ["고마워요. …조금 숨이 쉬어지네요."],
        "pressure_null": ["그렇게 몰아세우면 누구라도 무너져요."],
        "pressure_crew": ["제가 아는 건 다 말했어요. 정말이에요."],
        "deny": ["{room}엔 가지 않았어요. 거긴 제가 갈 일이 없는 곳이에요.", "그건 제가 아니에요."],
        "excuse_remote": ["생태 단말은 원격 동기화가 돌아요. 제가 거기 있었던 게 아니에요."],
        "excuse_auto": ["자동 관리 주기였을 거예요."],
        "excuse_card": ["제 태그는 작업대에 두고 다녀요. 누가 가져갔을 수도요."],
        "counter": ["{target|i} 그렇게 말했어요? {target}도 그때 어디 있었는지 똑바로 말 안 했잖아요."],
        "counter_soft": ["{target|i}… 왜 그렇게 말했을까요."],
        "partial_admit": ["…맞아요. {room} 앞까지는 갔어요. 안에서는 아무것도 안 했어요. {pos|ira}고 한 건 거짓말이었어요."],
        "vouch_hold": ["{target|wa} 같이 있었어요. 정말이에요."],
        "already_told": ["아까 다 말했어요."],
        "deflect": ["그건… 지금 말하고 싶지 않아요.", "사건이랑은 상관없는 일이에요."],
        "explain_with": ["저는 {pos}에 있었어요. {mate}한테 물어봐요.", "{mates|wa} 같이 있었어요. {source|i} 본 건 제가 아니에요."],
        "explain_alone": ["혼자 있었어요. 그래도 {room} 쪽엔 가지 않았어요. 정말로요."],
        "misremember": ["아, 제가 착각했어요. {pos|ieot}어요. 물 주는 순서를 거꾸로 기억했네요."],
        "confess": ["…사실대로 말할게요. 그때 {pos}에 있었어요."],
        "confess_pressed": ["알겠어요. 숨기지 않을게요. {pos|ieot}어요."],
        "incident_note": ["{time}, {room|ieyo}. {stake|i} 걸린 일이에요. 살아 있는 것부터 확인할게요."],
        "recovered_record": ["{from}의 기록이 생태 백업에 남아 있었어요. 어제 그 시간 거예요."],
        "morning_mourn": ["{victim}… 어제 물 준 화분, 아직 촉촉한데."],
        "morning_resolve": ["슬픈 건 나중에요. 지금은 남은 사람을 지켜야 해요."],
        "morning_relief": ["{target|i} 무사해요. 다행이에요, 정말."],
        "morning_attacked_meaning": ["{target|eul} 노렸다는 건… {target|i} 뭔가 알고 있다는 거겠죠."],
        "morning_quiet": ["밤은 조용했어요. 그래도 다들 잠은 못 잔 얼굴이네요."],
        "morning_after_vote": ["{target}의 포드 온도는 괜찮아요. …그래도 마음이 무거워요."],
        "after_isolation": ["격리 뒤에도 상태가 달라지는지 제가 기록할게요."],
        "last_plea": ["제 화분에 물 좀 부탁해요. 금방 돌아올게요.", "누구를 보내든, 그 사람도 우리 중 하나예요. 그것만 잊지 마요.", "제가 평소랑 달라 보였다면… 저도 무서웠나 봐요."],
        "m_record": ["제가 맡은 기록이에요. {record}"],
        "m_group_answer": ["{members} 중에 저도 있네요. 저는 식물 곁에 있었어요."],
        "m_caution": ["{target}에게 너무 몰아가지 마요. 확실한 걸 먼저 봐요."],
        "m_saw": ["봤어요. {time}쯤 {target|i} {room} 쪽으로 갔어요."],
        "m_saw_group": ["{time}쯤 {phrase} {room} 쪽으로 갔어요. {members} 중 한 명이에요."],
        "m_defend_self": ["저는 {pos}에 있었어요. {mates|wa} 같이요. {target}, 왜 그렇게 생각해요?"],
        "m_vouch": ["{target|eun} 그때 저랑 {pos}에 있었어요."],
        "m_catch_lie": ["{a}의 말이랑 {b}의 말이 안 맞아요. 둘 다 맞을 수는 없어요."],
        "m_benign_callout": ["{target}, {mate|i} 당신이랑 같이 있었다는데요. {pos|ieot}다는 건 뭐예요?"],
        "m_deflect": ["그건 나중에 말할게요."],
        "m_confess_public": ["…다들 앞에서 말할게요. 그 시간엔 {pos}에 있었어요."],
        "m_callback": ["{target}, {when} {old|ira}고 했잖아요. 지금은 {new|ieyo}?"],
        "m_deny": ["아니에요.", "그렇게 말한 적 없어요."],
        "m_yesterday": ["어제 {target|eul} 보냈는데 오늘도 일이 생겼어요. …우리가 틀렸을까요?"],
        "m_forward": ["그래도 오늘은 제대로 골라요. 남은 사람을 위해서요."],
        "m_accuse": ["{target}. {reason|i} 계속 걸려요. 미안해요, 그래도 말해야겠어요."],
        "m_agree": ["저도 {target} 쪽이 마음에 걸려요."],
        "m_excuse_remote": ["원격 동기화였을 거예요. 저는 {room}에 없었어요."],
        "m_excuse_auto": ["자동 관리 주기예요."],
        "m_excuse_card": ["누가 제 태그를 가져갔을 수도 있어요."],
        "m_rebut": ["음… 그건 그렇게 되지 않아요. {fact}"],
        "m_demand": ["{target}, 다시 설명해 줘요. 천천히."],
        "m_shift": ["…다시 생각해 보니 {target|ieyo}. {reason|i} 걸려요."],
        "m_confirm": ["네, 제가 말한 거예요."],
        "m_retreat": ["…제가 잘못 봤을 수도 있어요. {target|ira}고 한 건 미안해요."],
        "m_thanks": ["고마워요. 정말로요."]
    }
}

# Generic fallbacks so a missing key never shows an empty line.
# 1.0 final words: what the person answers is the actual thing that was
# raised against them (a link that held, a harmless reason now public, the
# explorer's own accusation). Same words for Nulls and innocents.
const LAST_LINES := {
    "mira": {"last_link": ["그 두 기록이 안 맞는다는 건 알아요. 그래도 그 틈을 제가 만들었다는 증거는 아니에요. 한 번만 더 봐 줘요.",
            "두 기록이 충돌하는 건 맞아요. 하지만 그 사이에 사람이 다쳤는지, 제가 실제로 뭘 했는지는 따로 봐 주세요."],
        "last_explained": ["숨긴 이유는 이미 말했어요. 부끄러웠지만, 사건과는 상관없어요. 그걸로 저를 보내진 말아요.",
            "제가 감춘 건 사람 상태에 관한 일이었어요. 사건 흔적과 섞지 말고, 제가 설명한 범위만 판단해 주세요."],
        "last_accused_by_you": ["당신이 저를 지목한 이유는 들었어요. 저는 그 이유가 틀렸다고 생각해요. 판단은… 당신 몫이에요.",
            "저를 의심한 이유는 알아요. 그래도 오늘 제 행동이 누구에게 어떤 결과를 냈는지도 같이 봐 주세요."]},
    "rho": {"last_link": ["그래, 그 둘 안 맞아. 인정해. 근데 안 맞는 거랑 내가 했다는 건 다른 얘기잖아.",
            "로그랑 내 말이 안 맞는 건 맞아. 근데 패널을 누가 실제로 만졌는지는 흔적부터 다시 봐."],
        "last_explained": ["내가 뭘 숨겼는지는 다 말했어. 창피한 거지 사건이랑은 상관없어.",
            "내 실수는 내 실수라고 했어. 고친 흔적이랑 누가 망가뜨린 흔적은 같은 게 아니야."],
        "last_accused_by_you": ["너 나 찍었지. 괜찮아. 대신 틀렸으면, 내일 그 얘기 꼭 하자.",
            "나 의심한 건 알겠어. 마지막으로 공구 순서랑 작업 시간만 다시 봐. 손댄 건 거기에 남아."]},
    "dax": {"last_link": ["모순은 인정해. 남은 변수는 아직 두 개야. 그중 하나를 골라서 나로 끝내지는 마.",
            "그 연결로 한 조건은 깨졌어. 아직 설명 가능한 경우가 남아 있어. 전제를 하나 더 확인해."],
        "last_explained": ["숨긴 건 설명했어. 조건 하나가 빠졌다고 결론이 바뀌진 않아.",
            "빠뜨린 가정은 인정했어. 이제 그 가정을 빼고도 같은 결론이 나오는지 계산해."],
        "last_accused_by_you": ["네 추론은 들었어. 전제 하나가 틀렸다고 봐. 계산은 네가 해.",
            "나를 고른 논리는 이해해. 다만 그 결론이 성립하려면 아직 확인 안 된 조건 하나가 필요해."]},
    "noa": {"last_link": ["두 기록이 부딪힌다는 건 저도 적었어요. 누가 그 틈을 만들었는지는 아직 안 적혀 있어요.",
            "원문 둘이 충돌해요. 하지만 작성자와 수정 시각까지 같은 결론을 말하는 건 아니에요."],
        "last_explained": ["숨긴 이유는 말했어요. 기록에도 남겼어요. 그 이상은 없어요.",
            "왜 공개하지 않았는지는 기록에 적었어요. 원문과 제 판단을 같은 문장으로 만들진 말아 주세요."],
        "last_accused_by_you": ["당신의 지목도 적었어요. 틀렸다면, 그것도 적을 거예요.",
            "저를 지목한 근거는 남겼어요. 마지막으로 누가 언제 처음 기록했는지만 확인해 주세요."]},
    "sena": {"last_link": ["그 연결, 틀렸다고는 안 할게. 근데 안 맞는 게 하나 있다고 사람을 재우는 거야?",
            "시간이 어긋난 건 인정해. 그래도 문이 열린 순서랑 내가 지나간 순서는 따로 봐."],
        "last_explained": ["숨긴 건 말했잖아. 내 실수였어. 사건이랑은 상관없어.",
            "내가 절차 넘긴 건 인정했어. 그 시간에 어느 문을 통과했는지는 기록대로 봐."],
        "last_accused_by_you": ["날 찍은 거 알아. 좋아. 대신 네 판단이 맞는지 끝까지 봐.",
            "나를 고른 이유 들었어. 마지막으로 출입 순서 확인해. 누가 먼저 들어왔는지는 안 바뀌어."]},
    "vale": {"last_link": ["…시간이 겹치는 건 알아요. 그게 전부예요.",
            "…겹쳐 들린 건 맞아요. 그래도 원음과 전해 들은 말은 다른 트랙이에요. 같이 섞진 말아 주세요."],
        "last_explained": ["…이유는 말했어요. 더는 없어요.",
            "…제가 숨긴 이유는 말했어요. 이제 제 목소리인지, 누가 전한 목소리인지부터 나눠 들어 주세요."],
        "last_accused_by_you": ["…당신이 그렇게 들었다면요. 전 다르게 들었어요.",
            "…저를 의심한 건 알아요. 마지막으로 원음의 간격만 한 번 더 들어 주세요. 말보다 먼저 남는 게 있어요."]},
    "eli": {"last_link": ["안 맞는 건 인정한다. 내가 했다는 건 아니야.",
            "좌표가 겹치는 건 맞아. 그 위치에 갈 수 있었다는 것과 실제로 간 건 다르다."],
        "last_explained": ["이유는 말했다. 끝.",
            "경로를 바꾼 이유는 말했다. 이제 거리와 이동 시간으로 확인해."],
        "last_accused_by_you": ["네 판단이다. 책임도 네 거고.",
            "나를 고를 거면 이동 가능 시간부터 봐. 길은 의견이 아니라 거리야."]},
    "lyra": {"last_link": ["그 두 가지가 안 맞는 건 저도 봤어요. 그래도 한 가지 흔적으로 사람 전체를 판단하진 말아 줘요.",
            "흔적이 다르게 자란 건 맞아요. 그런데 환경이 달랐는지, 사람이 건드렸는지는 아직 나눠 봐야 해요."],
        "last_explained": ["숨긴 이유는 이미 말했어요. 창피했을 뿐이에요. 그건 사건이 아니에요.",
            "제가 감춘 건 표본을 더 보고 싶어서였어요. 그 선택과 누가 사건을 만들었는지는 따로 봐 주세요."],
        "last_accused_by_you": ["당신이 저를 의심하는 건 알아요. 괜찮아요. 다만 끝까지 확인은 해 줘요.",
            "저를 의심해도 괜찮아요. 마지막으로 생장선과 환경 기록을 같이 봐 주세요. 살아 있는 흔적은 순서를 남겨요."]},
}

# 1.0 linking: the room answers a statement-and-evidence link.
const LINK_LINES := {
    "mira": {"m_link_holds": ["…그 두 가지는 같이 설명이 안 돼요. {target}, 이건 대답해 줘야 해요.",
            "사람 상태 기록하고 그 설명이 동시에 맞기 어려워요. {target}, 어느 쪽이 달랐는지 말해 주세요."],
        "m_link_partial": ["그것만으로는 아직 누구라고 할 수 없어요. 그래도 기억해 둘게요.",
            "가능성은 줄었어요. 사람을 보내기 전엔 실제 행동까지 한 번 더 확인해요."],
        "m_link_fails": ["그 둘은 서로 상관없는 얘기 같아요. 괜히 사람을 몰지는 말아요.",
            "그 기록이 사람 상태를 말해 주진 않아요. 결과가 다른 얘기라면 억지로 묶지 말아요."],
        "m_redirect": ["제 말만 보지 말고 {target}의 설명도 봐요. 아직 안 맞는 게 거기 있잖아요."],
        "m_doubt_explorer": ["탐사요원, 정말 확실해요? 그 연결은 당신이 만든 거예요."]},
    "rho": {"m_link_holds": ["와, 그건 진짜 안 맞네. {target}, 이건 설명해야겠다.",
            "잠깐, 작업 순서대로 놓으면 둘이 같이 있을 수가 없는데? {target}, 어디서 달라진 거야?"],
        "m_link_partial": ["음, 반쯤은 맞는 말인데… 아직 확정은 아니지?",
            "장비 흔적 하나는 맞아. 근데 손댄 순서까지 알아야 누군지 말할 수 있지."],
        "m_link_fails": ["어… 그게 왜 연결돼? 난 잘 모르겠는데.",
            "그건 다른 부품 얘기잖아. 실제로 이어진 선부터 봐. 그 둘은 안 붙어 있어."],
        "m_redirect": ["나만 보지 말고, {target} 쪽은? 거기도 안 맞는 게 있었잖아."],
        "m_doubt_explorer": ["야, 너 아까부터 너무 확신하는 거 아냐? 그 연결, 네가 붙인 거잖아."]},
    "dax": {"m_link_holds": ["조건 두 개가 서로를 지워. {target}, 남은 설명을 들어 보자.",
            "둘을 동시에 참이라고 두면 조건이 깨져. {target}, 빠진 전제가 뭔지 말해."],
        "m_link_partial": ["범위는 줄었어. 결론은 아직이야.",
            "후보 조건 하나는 제거됐어. 남은 변수까지 보기 전엔 사람 하나로 못 줄여."],
        "m_link_fails": ["그 둘 사이엔 논리가 없어. 추측을 근거처럼 말하지 마.",
            "공통 변수가 없어. 같은 시간에 있었다는 이유만으로 인과를 만들진 마."],
        "m_redirect": ["변수를 하나만 보지 마. {target} 쪽 모순은 아직 그대로야."],
        "m_doubt_explorer": ["그 연결을 한 건 너야. 네 추론이 틀릴 가능성도 계산에 넣어."]},
    "noa": {"m_link_holds": ["적어 둘게요. 두 기록이 부딪혀요. {target}의 답도 같이요.",
            "원문 기준으로 두 문장이 동시에 성립하지 않아요. {target}, 어느 기록을 직접 봤는지부터 말해 주세요."],
        "m_link_partial": ["적어 둘게요. 다만 이건 확인이 아니라 후보예요.",
            "출처 하나는 맞아요. 작성 시각과 옮긴 사람까지 확인하면 범위를 더 줄일 수 있어요."],
        "m_link_fails": ["그 기록은 그 말과 관계가 없어요. 그렇게는 못 적어요.",
            "작성자가 다른 기록이에요. 같은 문장처럼 묶으면 원문에 없는 의미가 생겨요."],
        "m_redirect": ["{target}의 진술도 아직 정리가 안 됐어요. 그것도 같이 봐요."],
        "m_doubt_explorer": ["그 연결은 탐사요원의 해석이에요. 기록에 적힌 건 아니에요."]},
    "sena": {"m_link_holds": ["그건 빠져나갈 데가 없네. {target}, 말해 봐.",
            "출입 순서가 네 말하고 안 맞아. {target}, 어느 문을 먼저 지났는지 다시 말해."],
        "m_link_partial": ["좁혀지긴 했네. 한 방은 아니야.",
            "동선 하나는 걸려. 근데 문이 열린 순서까지 맞춰야 사람 하나로 줄어."],
        "m_link_fails": ["그걸로 누굴 몰아? 근거가 안 되잖아.",
            "그 기록으론 출입 순서가 안 나와. 문 하나 건너뛰고 사람부터 정하지 마."],
        "m_redirect": ["그럼 {target|eun}? 거기 문제는 벌써 잊었어?"],
        "m_doubt_explorer": ["너 너무 몰아가는데? 그 연결 확실해?"]},
    "vale": {"m_link_holds": ["…시간이 겹쳐요. {target}, 이 부분은 들어야겠어요.",
            "…원음 간격하고 그 말의 시각이 겹쳐요. {target}, 이건 직접 들은 건지 전해 들은 건지 말해 주세요."],
        "m_link_partial": ["…그 말만으로는 아직 모자라요. 다른 쪽에서 한 번 더 들어야 해요.",
            "…패턴은 비슷해요. 그래도 원출처가 하나 더 있어야 같은 목소리라고 할 수 있어요."],
        "m_link_fails": ["…그건 다른 얘기예요. 섞으면 더 헷갈려요.",
            "…전언 사이에서 바뀐 말 같아요. 원음하고 같은 줄에 놓으면 안 돼요."],
        "m_redirect": ["…{target}의 말도 아직 설명되지 않았어요."],
        "m_doubt_explorer": ["…당신이 그렇게 이어 붙였을 뿐이잖아요."]},
    "eli": {"m_link_holds": ["위치가 안 맞는다. {target}, 설명해.",
            "거리와 시간이 안 맞아. {target}, 네가 말한 경로로는 그 시각에 도착 못 해."],
        "m_link_partial": ["후보는 줄었다. 아직 하나는 아니야.",
            "갈 수 있는 경로는 줄었어. 어느 길을 썼는지 확인해야 하나로 좁혀."],
        "m_link_fails": ["관계없다. 헛짚었어.",
            "그 두 위치는 같은 경로에 안 있어. 지도에서 먼저 이어 봐."],
        "m_redirect": ["{target} 쪽 동선도 확인 안 됐다."],
        "m_doubt_explorer": ["네 해석이다. 사실이 아니야."]},
    "lyra": {"m_link_holds": ["그 둘을 나란히 두니까 이상하네요. {target}, 무슨 일이었는지 얘기해 줄래요?",
            "환경 기록하고 남은 생장 흔적이 같이 맞지 않아요. {target}, 언제 이 상태를 처음 봤어요?"],
        "m_link_partial": ["방향은 보여요. 조금만 더 확인해 봐요.",
            "변화는 실제예요. 다만 사람 손인지 환경 때문인지는 표본을 하나 더 봐야 해요."],
        "m_link_fails": ["음… 그건 좀 억지 같아요. 조금만 더 차분히 봐요.",
            "그 흔적은 같은 원인이라고 보기 어려워요. 자란 시간부터 다르잖아요."],
        "m_redirect": ["저만 보지 말고 {target}의 이야기도 다시 들어 봐요."],
        "m_doubt_explorer": ["탐사요원, 너무 서두르는 것 같아요. 그 연결은 당신 생각이잖아요."]},
}

const FALLBACK := {
    "open_with": "{time}엔 {pos}에 있었어. {mates|wa} 같이.",
    "open_alone": "{time}엔 {pos}에 혼자 있었어.",
    "saw_none": "아무도 못 봤어.",
    "deny": "나는 {room}에 가지 않았어.",
    "opinion": "{target|i} 걸려. {reason|i} 설명이 안 돼.",
    "opinion_none": "아직 모르겠어.",
    "m_deny": "그건 사실이 아니야."
}

static func line(npc_id: String, key: String, params: Dictionary = {}, pick: float = 0.0) -> String:
    var pool: Array = LINES.get(npc_id, {}).get(key, [])
    if pool.is_empty():
        pool = MORE.get(npc_id, {}).get(key, [])
    if pool.is_empty():
        pool = MORE2.get(npc_id, {}).get(key, [])
    if pool.is_empty():
        pool = RECORD_OTHER.get(npc_id, {}).get(key, [])
    if pool.is_empty():
        pool = HEARSAY_LINES.get(npc_id, {}).get(key, [])
    if pool.is_empty():
        pool = SHIELD_LINES.get(npc_id, {}).get(key, [])
    if pool.is_empty():
        pool = ANALYST_LINES.get(npc_id, {}).get(key, [])
    if pool.is_empty():
        pool = LINK_LINES.get(npc_id, {}).get(key, [])
    if pool.is_empty():
        pool = LAST_LINES.get(npc_id, {}).get(key, [])
    var template := ""
    if pool.is_empty():
        template = str(FALLBACK.get(key, ""))
    else:
        template = str(pool[int(clampf(pick, 0.0, 0.999) * pool.size()) % pool.size()])
    if template == "":
        return ""
    return AstraJosa.fill(template, params)

static func has_line(npc_id: String, key: String) -> bool:
    return not Array(LINES.get(npc_id, {}).get(key, [])).is_empty() or not Array(MORE.get(npc_id, {}).get(key, [])).is_empty()

# Why an innocent lied, in their own words: the fixed personal secret from
# AstraCrewCatalog, framed by the kind of reason this Day's packet gave them.
const REASON_LEAD := {
    "EMBARRASSMENT": "창피해서 말을 돌렸어요.",
    "PROTECT_OTHER": "누군가를 감싸려고 했어요.",
    "HIDE_MISTAKE": "제 실수를 감추고 싶었어요.",
    "KEEP_PROMISE": "누군가와 한 약속이 있었어요.",
    "PERSONAL_SECRET": "사건과는 상관없는 제 일이에요.",
    "FEAR": "무서워서 제대로 말을 못 했어요.",
    "MISREMEMBERED": "착각이었어요."
}

static func secret(npc_id: String, reason: String, _pos: String) -> String:
    var base := str(AstraCrewCatalog.info(npc_id).get("secret", ""))
    var lead := str(REASON_LEAD.get(reason, ""))
    if npc_id in ["rho", "dax", "sena", "eli"]:
        lead = lead.replace("했어요", "했어").replace("있었어요", "있었어").replace("싶었어요", "싶었어").replace("이에요", "이야").replace("었어요", "었어").replace("에요", "야")
    return (lead + " " + base).strip_edges()

# ---------------------------------------------------------------- 0.8.0 final pass
# Second-level meeting play (contested excuses, a pressed sighting, a friend's
# character reference), voiced ballots, callbacks to what the explorer did
# yesterday, and small human habits. Same rule as above: every line must be
# sayable by an innocent and by a Null in the same situation.
const MORE := {
    "mira": {
        "m_excuse_again": ["{expert|i} 말하는 건 표준 설정이에요. 지난 점검 때 의료 단말 설정이 바뀌었어요. 그건 확인해 봤어요?"],
        "m_settle": ["다시 확인할게요. …아니에요. 그 장비에는 예외 설정이 없어요. {target}, 그 설명은 맞지 않아요."],
        "m_hold_sighting": ["확실해요. {time}쯤이었고, 틀림없이 {target|ieyo}. 걸음걸이를 알아요."],
        "m_vouch_character": ["{target|eun} 그럴 사람이 아니에요. 제가 옆에서 봐 왔어요."],
        "m_basis": ["근거요? {reason|ieyo}. 그게 설명되기 전까지는 {target|eul} 믿기 어려워요."],
        "m_basis_thin": ["…확실한 근거는 아니에요. 그냥 {target}의 대답이 계속 짧았어요."],
        "m_note_thin": ["그럼 지금 건 의심이 아니라 불안이에요. 둘은 구분해요."],
        "m_defend_alone": ["저는 {pos}에 있었어요. 혼자였던 건 맞아요. {target}, 그걸로 저를 의심하는 거예요?"],
        "vote_evidence": ["{target}. {reason|i} 끝까지 설명되지 않았어요."],
        "vote_follow": ["…{pusher}의 판단을 믿어 볼게요. {target|ieyo}."],
        "vote_player": ["탐사요원의 말을 믿을게요. {target|ieyo}."],
        "vote_unsure": ["…정말 모르겠어요. 그래도 골라야 한다면 {target|ieyo}. 미안해요."],
        "last_plea_secret": ["숨긴 게 있는 건 맞아요. 하지만 여러분이 찾는 이유와는 달라요."],
        "after_isolation_close": ["…{target}, 금방 다시 깨울게요. 약속해요."],
        "open_after_accused": ["어제 저를 지목했죠. 괜찮아요. 오늘은 제 말을 끝까지 들어 줘요."],
        "open_after_defended": ["어제 저를 변호해 줘서 고마웠어요. 오늘은 제가 도울게요."],
        "habit": ["잠깐만요. …얼굴이 창백해요. 물부터 마셔요. 그다음에 물어봐요.", "숨 한번 쉬고요. 네, 말해요."]
    },
    "rho": {
        "m_excuse_again": ["그건 신형 기준이고. 여기 건 예전 펌웨어야. 예전 거면 원격도 먹혀. …아마."],
        "m_settle": ["펌웨어? 그 모델은 처음부터 원격이 막혀 있어. 내가 직접 교체했다고. {target}, 그거 아니야."],
        "m_hold_sighting": ["확실하다니까. 틀림없이 {target|ieot}어. 그 시간에 그쪽 가는 사람이 몇이나 된다고."],
        "m_vouch_character": ["야, {target|eun} 아니야. 같이 일해 봤으면 알아. 그런 짓 할 사람 아니라고."],
        "m_basis": ["근거? {reason}. 그거면 충분하잖아."],
        "m_basis_thin": ["…솔직히 감이야. 근데 내 감은 잘 맞거든."],
        "m_note_thin": ["감으로 사람을 보내자고? 그건 좀 아니지."],
        "m_defend_alone": ["{pos}에 있었어. 혼자. 그게 죄야? {target}, 근거 대."],
        "vote_evidence": ["{target}. {reason}, 그거 하나면 돼."],
        "vote_follow": ["{pusher} 말이 맞는 것 같아. {target}."],
        "vote_player": ["네가 그렇게 봤다면. {target}."],
        "vote_unsure": ["모르겠다. 찍는 거 진짜 싫은데… {target}."],
        "last_plea_secret": ["그래, 나 숨긴 거 있어. 근데 그거 이 사건이랑 상관없어. 진짜야."],
        "after_isolation_close": ["{target}… 야, 거기서 너무 춥게 자지 마라."],
        "open_after_accused": ["어제는 나부터 보내자며. 오늘은 무슨 바람이야?"],
        "open_after_defended": ["어제 편 들어줘서 고마웠어. 뭐든 물어봐."],
        "habit": ["(렌치로 패널을 톡톡 두드린다) 이거 소리가 계속 거슬려서. 응, 물어봐.", "밥은 먹었어? 아니, 그냥. 다들 굶은 얼굴이라서."]
    },
    "dax": {
        "m_excuse_again": ["원칙적으로는 {expert} 말이 맞아. 그런데 예외 경로가 하나 있어. 내가 설계했으니까 알아."],
        "m_settle": ["조건을 하나씩 보자. 예외 경로는 관리자 인증이 있어야 열려. 그 시간 관리자 인증은 없었어. 성립 안 해."],
        "m_hold_sighting": ["조명이 어두웠던 건 인정해. 그래도 체형과 동선을 보면 {target|ieot}어."],
        "m_vouch_character": ["근거는 아니지만 말해 둘게. {target|eun} 그런 식으로 움직이는 사람이 아니야."],
        "m_basis": ["정리하면 이래. {reason}. 다른 설명이 있으면 듣겠어."],
        "m_basis_thin": ["인정할게. 지금 건 추론이지 증거는 아니야."],
        "m_note_thin": ["근거 없는 지목은 확률을 올리지 않아. 빼고 가자."],
        "m_defend_alone": ["{pos}. 혼자였어. 증인이 없다는 건 증거가 아니야, {target}."],
        "vote_evidence": ["{target}. {reason}. 계산은 그렇게 나와."],
        "vote_follow": ["내 계산은 아직 반반이야. {pusher} 쪽 근거를 따르지. {target}."],
        "vote_player": ["네 근거를 받아들일게. {target}."],
        "vote_unsure": ["데이터가 모자라. 남은 변수 중에선 {target}."],
        "last_plea_secret": ["숨긴 게 있다는 건 인정해. 다만 그 변수는 이 사건과 독립이야."],
        "after_isolation_close": ["{target}. …나중에 네가 옳았다고 말할 기회가 있으면 좋겠군."],
        "open_after_accused": ["어제 네 표는 나였지. 그 판단 근거부터 듣고 싶군."],
        "open_after_defended": ["어제 네가 나를 변호했지. 빚은 정확히 갚는 편이야."],
        "habit": ["조건부터 정리하자. 네가 묻고, 나는 아는 것만 답해. 모르는 건 모른다고 할게.", "커피가 식었군. 뭐, 괜찮아. 물어봐."]
    },
    "noa": {
        "m_excuse_again": ["{expert}의 말은 일반적인 경우예요. 이 구역 장비는 설정 기록이 두 번 바뀌었어요."],
        "m_settle": ["설정 기록을 다시 봤어요. 바뀐 적 없어요. 한 번도요."],
        "m_hold_sighting": ["{time}. {room} 쪽. {target}. 제가 적은 그대로예요."],
        "m_vouch_character": ["{target|eun} 지금까지 말을 한 번도 바꾸지 않았어요. 그것도 기록이에요."],
        "m_basis": ["{reason|ieyo}. 제가 적은 그대로예요."],
        "m_basis_thin": ["…기록은 없어요. 인상만 있어요. 그렇게 적어 둘게요."],
        "m_note_thin": ["‘근거 없음.’ 그렇게 적을게요."],
        "m_defend_alone": ["{pos}에 있었어요. 혼자요. {target}, 그건 제가 기억하는 것과 달라요."],
        "vote_evidence": ["{target}. {reason}. 기록대로예요."],
        "vote_follow": ["확신은 없어요. {pusher}의 말을 기록하고, {target}."],
        "vote_player": ["탐사요원의 판단을 따를게요. {target}."],
        "vote_unsure": ["근거 부족. 그래도 {target}. 이렇게 적어 둘게요."],
        "last_plea_secret": ["말하지 않은 게 있어요. 그래도 거짓 기록은 남기지 않았어요."],
        "after_isolation_close": ["{target}의 마지막 말, 그대로 적어 둘게요. 한 글자도 안 바꿀게요."],
        "open_after_accused": ["어제 저를 지목했어요. 기록해 뒀어요. …그래도 대답은 할게요."],
        "open_after_defended": ["어제 저를 변호했어요. 그것도 적어 뒀어요."],
        "habit": ["(시각부터 적는다) 네. 시작해요.", "‘물어볼 게 있다.’ …적었어요. 말해요."]
    },
    "sena": {
        "m_excuse_again": ["그건 정상 상황 얘기지. 비상 모드에선 권한 체계가 달라. 나도 몇 번 겪었어."],
        "m_settle": ["비상 모드는 그 시간에 안 켜졌어. 보안 로그에 남아. {target}, 말이 안 돼."],
        "m_hold_sighting": ["내가 사람 얼굴을 잘못 볼 일은 없어. 틀림없이 {target|ieot}어."],
        "m_vouch_character": ["{target|eun} 내가 보증해. 내가 틀리면 나도 같이 책임질게."],
        "m_basis": ["{reason}. 보안 쪽에선 그거 하나로도 격리 사유야."],
        "m_basis_thin": ["증거? 없어. 근데 위험한 건 먼저 막는 게 내 일이야."],
        "m_note_thin": ["근거 없으면 표에서 빼. 그게 공정한 거야."],
        "m_defend_alone": ["{pos}에 있었어. 혼자였어. {target}, 날 의심하려면 제대로 해."],
        "vote_evidence": ["{target}. {reason}. 망설일 이유 없어."],
        "vote_follow": ["{pusher} 말대로 {target}. 틀리면 내가 책임질게."],
        "vote_player": ["좋아, 네 말 믿는다. {target}."],
        "vote_unsure": ["확신은 없어. 위험해 보이는 쪽. {target}."],
        "last_plea_secret": ["내가 숨긴 건 있어. 근데 네가 찾는 이유랑은 달라."],
        "after_isolation_close": ["{target}, 포드 문 앞은 내가 지킨다. 그건 약속해."],
        "open_after_accused": ["어제는 나부터 격리하자고 했잖아. 오늘은 뭐가 달라졌는데?"],
        "open_after_defended": ["어제 고마웠어. 이번엔 내가 네 뒤를 볼게."],
        "habit": ["(문 쪽을 한 번 확인한다) 좋아. 여기선 말해도 돼.", "다들 지금 어디 있는지 알아? …됐어, 나중에. 물어봐."]
    },
    "vale": {
        "m_excuse_again": ["…{expert} 말도 맞아요. 그런데 신호가 돌아서 들어오면 인증이 늦게 찍히기도 해요."],
        "m_settle": ["신호 지연 기록을 봤어요. 그 시간엔 지연이 없었어요. 인증은 바로 찍혔어요."],
        "m_hold_sighting": ["…발소리도 들었어요. {target}의 걸음이었어요."],
        "m_vouch_character": ["…{target}의 목소리는 평소랑 같아요. 거짓말하는 사람 목소리는 달라져요."],
        "m_basis": ["{reason|ieyo}. 제가 들은 것 중에선 그게 제일 분명해요."],
        "m_basis_thin": ["…아직은 느낌이에요. 확신은 없어요."],
        "m_note_thin": ["…출처 없는 말이었네요."],
        "m_defend_alone": ["…{pos}에 있었어요. 혼자서요. {target}, 왜 그렇게 생각해요?"],
        "vote_evidence": ["{target|ieyo}. {reason|i} 제일 분명해요."],
        "vote_follow": ["…{pusher}의 말이 제일 또렷했어요. {target|ieyo}."],
        "vote_player": ["탐사요원님 말을 따를게요. {target|ieyo}."],
        "vote_unsure": ["…{target|ieyo}. 확신은 없어요."],
        "last_plea_secret": ["…말 못 한 게 있어요. 하지만 그건 누구를 해치는 일이 아니었어요."],
        "after_isolation_close": ["…{target}의 목소리, 마지막까지 떨리지 않았어요."],
        "open_after_accused": ["…어제 제 이름을 말하셨죠. 오늘은 제가 먼저 들을게요."],
        "open_after_defended": ["어제는… 고마웠어요."],
        "habit": ["(한쪽 이어폰을 뺀다) …네. 듣고 있어요.", "잠깐만요. 이 잡음만. …됐어요."]
    },
    "eli": {
        "m_excuse_again": ["구형 장비면 얘기가 달라. 그 구역은 아직 교체 안 됐어."],
        "m_settle": ["교체 기록 있어. 그 구역은 지난 정박 때 바꿨어. 구형 아니야."],
        "m_hold_sighting": ["그 시각, 그 위치. {target|ieot}어. 틀림없어."],
        "m_vouch_character": ["{target|eun} 아니야. 이유는 설명 못 해. 그냥 알아."],
        "m_basis": ["{reason}. 그게 다야."],
        "m_basis_thin": ["증거는 없어. 동선이 이상했을 뿐이야."],
        "m_note_thin": ["증거 없으면 다음."],
        "m_defend_alone": ["{pos}. 혼자였어. {target}, 그 시각에 날 봤어?"],
        "vote_evidence": ["{target}. {reason}."],
        "vote_follow": ["{pusher|rang} 같은 쪽. {target}."],
        "vote_player": ["네 판단에 건다. {target}."],
        "vote_unsure": ["{target}. 이유는 약해."],
        "last_plea_secret": ["숨긴 건 있어. 이 일이랑은 무관해."],
        "after_isolation_close": ["…{target}. 다음 항로는 같이 맞추자."],
        "open_after_accused": ["어제 날 찍었지. 됐어. 물어봐."],
        "open_after_defended": ["어제 일, 기억해. 물어봐."],
        "habit": ["(출입구와 시계를 확인한다) 됐어. 말해.", "여기 시계 2분 늦어. 기준은 내 걸로 해."]
    },
    "lyra": {
        "m_excuse_again": ["그건 규정상 그렇다는 거죠. 실제로는 자동 주기가 꼬일 때가 있어요. 제가 봤어요."],
        "m_settle": ["자동 주기 표를 봤어요. 그 시간엔 주기가 없어요. 누군가 직접 했어요."],
        "m_hold_sighting": ["틀림없이 {target|ieyo}. 제가 인사까지 했는걸요."],
        "m_vouch_character": ["{target|eun} 평소랑 똑같아요. 사람이 그렇게 갑자기 변하지 않아요."],
        "m_basis": ["{reason|ieyo}. 제가 느낀 것만 말하는 게 아니에요."],
        "m_basis_thin": ["…근거라기보다, 오늘 {target}의 눈빛이 평소랑 달랐어요."],
        "m_note_thin": ["그럼 {target}한테 사과부터 해야겠네요."],
        "m_defend_alone": ["저는 {pos}에 있었어요. 혼자였어요. {target}, 왜 그렇게 생각해요?"],
        "vote_evidence": ["{target|ieyo}. {reason|i} 마음에 걸려요."],
        "vote_follow": ["{pusher|i} 그렇게 말했으니까요. {target|ieyo}."],
        "vote_player": ["당신을 믿어요. {target|ieyo}."],
        "vote_unsure": ["{target|ieyo}. …틀렸으면 좋겠어요."],
        "last_plea_secret": ["비밀은 있어요. 누구를 다치게 하는 비밀은 아니에요."],
        "after_isolation_close": ["{target}… 잘 자요. 일어나면 제일 먼저 인사할게요."],
        "open_after_accused": ["어제 저를 의심했죠. 조금 서운했어요. …그래도 물어봐요."],
        "open_after_defended": ["어제 제 편이 되어 줘서 정말 고마웠어요."],
        "habit": ["아, 왔어요? 여기 앉아요. 이 잎 좀 봐요, 오늘 새로 났어요.", "오늘은 아무도 말을 안 걸어서요. 와 줘서 좋아요."]
    }
}

# Lines for a caller who is also the witness of the discrepancy.
const MORE2 := {
    "mira": {"m_benign_callout_self": ["{target}, 그 시간엔 저랑 같이 있었잖아요. 그런데 왜 {pos|ira}고 했어요?"], "vote_lean": ["확신은 없어요. 그래도 {reason|i} 걸려요. {target|ieyo}."]},
    "rho": {"m_benign_callout_self": ["{target}, 너 그때 나랑 있었잖아. 근데 왜 {pos|ira}고 해?"], "vote_lean": ["확실하진 않은데… {reason}, 그게 걸려. {target}."]},
    "dax": {"m_benign_callout_self": ["{target}, 그 시간 넌 나와 같은 곳에 있었어. {pos|ira}는 말은 사실이 아니야."], "vote_lean": ["확률로만 보면 {target}. {reason}. 확정은 아니야."]},
    "noa": {"m_benign_callout_self": ["{target}. 그 시간 당신은 저랑 같이 있었어요. {pos|ira}는 말은 제 기억과 달라요."], "vote_lean": ["단정은 못 해요. {reason|i} 남아 있어요. {target}."]},
    "sena": {"m_benign_callout_self": ["{target}, 그때 너 나랑 있었잖아. {pos|ira}니, 왜 말을 바꿔?"], "vote_lean": ["완전히 확신하진 않아. 그래도 {reason}. {target}."]},
    "vale": {"m_benign_callout_self": ["…{target}, 그 시간엔 저랑 같이 있었잖아요. 왜 {pos|ira}고 했어요?"], "vote_lean": ["…{reason|i} 조금 더 걸려요. {target|ieyo}."]},
    "eli": {"m_benign_callout_self": ["{target}. 그때 나랑 같이 있었어. {pos|ira}는 건 틀려."], "vote_lean": ["확정은 아니야. {reason}. {target}."]},
    "lyra": {"m_benign_callout_self": ["{target}, 그 시간엔 저랑 같이 있었잖아요. {pos|ira}니요?"], "vote_lean": ["확실하지 않아요. 그래도 {reason|i} 마음에 걸려요. {target|ieyo}."],
        "record_open_other": ["{device|ieyo}. 제 담당은 아니지만 백업 권한으로 열 수 있어요."],
        "record_meaning_other": ["{members} 중 한 명이에요. 이것만으로는 한 사람이 안 나와요."], "record_meaning_specific_other": ["{target}의 인증이에요. 그 시간 거기 있었어요."]}
}

# A log outside the speaker's own job (a backup or a shared audit log): said
# plainly, with the device's real name.
const RECORD_OTHER := {
    "mira": {"hint_record_other": ["제 권한으로 열 수 있는 {device|i} 있어요. 그 시간이 남아 있을 거예요."], "record_open_other": ["{device|ieyo}. 제 담당은 아니지만 권한이 있어서 열 수 있어요."], "m_record_other": ["제 권한으로 연 기록 하나 공유할게요. {record}"],
        "record_meaning_other": ["{members} 중 누군가예요. 이것만으로 이름을 정하면 안 돼요."], "record_meaning_specific_other": ["{target}의 인증이 찍혀 있어요. 그 시간 거기 있었다는 뜻이에요."]},
    "rho": {"hint_record_other": ["{device}, 내 권한으로도 열려. 그 시간 거 남아 있을걸."], "record_open_other": ["{device}. 내 담당은 아닌데 권한은 있어. 열어 볼게."], "m_record_other": ["내 권한으로 기록 하나 열어 봤어. {record}"],
        "record_meaning_other": ["{members} 중 하나야. 딱 한 명까진 안 나와."], "record_meaning_specific_other": ["{target}의 인증이야. 기계는 거짓말 안 해."]},
    "dax": {"hint_record_other": ["{device|i} 있어. 내 쪽 권한으로 열 수 있어."], "record_open_other": ["{device|ieyo}? 내 설계 쪽 권한으로 열 수 있어."], "m_record_other": ["내 쪽 권한으로 연 기록, 공개하지. {record}"],
        "record_meaning_other": ["변수가 {members|ro} 줄었어. 조건 하나만 더 있으면 한 사람이 남아."], "record_meaning_specific_other": ["{target}의 인증이야. 원격 흔적은 없어."]},
    "noa": {"hint_record_other": ["백업 권한으로 볼 수 있는 {device|i} 있어요. 그 시간이 남아 있을 거예요."], "record_open_other": ["{device|ieyo}. 백업 권한으로 열게요. 그대로 읽을게요."], "m_record_other": ["백업 권한으로 연 기록, 그대로 읽을게요. {record}"],
        "record_meaning_other": ["한 사람으로 특정되진 않아요. {members} 중 한 명이에요."], "record_meaning_specific_other": ["{target}의 인증이에요. 그대로 적을게요."]},
    "sena": {"hint_record_other": ["{device}, 보안 권한으로 열 수 있어. 필요하면 말해."], "record_open_other": ["{device}. 보안 권한으로 열 수 있어."], "m_record_other": ["보안 권한으로 연 기록 공개한다. {record}"],
        "record_meaning_other": ["{members} 중 하나야. 이것만으론 못 찍어."], "record_meaning_specific_other": ["{target}의 인증이야. 그 시간 거기 있었어."]},
    "vale": {"hint_record_other": ["제가 열 수 있는 {device|i} 있어요. 그 시간 것도요."], "record_open_other": ["{device|ieyo}. 제 채널은 아니지만 열 수 있어요."], "m_record_other": ["제가 연 기록 하나 공유할게요. {record}"],
        "record_meaning_other": ["{members} 중 한 명이에요. 더 좁혀지진 않아요."], "record_meaning_specific_other": ["{target}의 인증이에요. 현장에서 찍힌 거예요."]},
    "lyra": {"hint_record_other": ["제가 볼 수 있는 {device|i} 있어요. 같이 열어 봐요."], "m_record_other": ["제가 본 기록 하나 보여 줄게요. {record}"]},
    "eli": {"hint_record_other": ["{device}. 내가 열 수 있어."], "record_open_other": ["{device}. 열 수 있어."], "m_record_other": ["기록. {record}"],
        "record_meaning_other": ["{members} 중 하나. 더는 안 좁혀져."], "record_meaning_specific_other": ["{target}. 그 시간 거기 있었어."]}
}

# 0.8.0 retold sightings in the meeting (§8): the listener says whose words
# they are, the witness confirms or corrects, someone notes that a detail
# changed on the way. Each in the speaker's own register.
const HEARSAY_LINES := {
    "mira": {
        "m_heard": ["{via|i} 그러는데, {time}쯤 {phrase} {room} 쪽으로 갔대요. 저는 직접 보진 못했어요."],
        "m_heard_named": ["{via|i} {time}쯤 {target|eul} {room} 쪽에서 봤다고 했어요. 제가 본 건 아니에요."],
        "m_source_correct": ["잠깐만요, 말이 바뀌었어요. 제가 본 건 {phrase} {room} 쪽으로 가는 거였어요."],
        "m_source_confirm": ["맞아요. 제가 본 거예요. 그대로 전해졌네요."],
        "m_note_relay": ["{a}의 잘못은 아니에요. 사람 사이를 건너면 말은 조금씩 바뀌어요."]
    },
    "rho": {
        "m_heard": ["{via|i} 그러던데? {time}쯤 {phrase} {room} 쪽으로 갔대. 난 못 봤어."],
        "m_heard_named": ["{via|i} 그러더라. {time}쯤 {target|eul} {room} 근처에서 봤대."],
        "m_source_correct": ["어? 그렇게 전해졌어? 아니야, 내가 본 건 {phrase} {room} 쪽으로 가는 거였어."],
        "m_source_confirm": ["어, 그거 내가 본 거 맞아."]
    },
    "dax": {
        "m_heard": ["{via}한테 들은 거야. {time}쯤 {phrase} {room} 쪽으로 갔대. 1차 정보는 아니야."],
        "m_heard_named": ["{via}한테 들은 거야. {time}쯤 {target|eul} {room} 근처에서 봤다더군. 2차 정보야."],
        "m_source_correct": ["전달 과정에서 값이 바뀌었네. 내가 본 건 {phrase} {room} 쪽으로 가는 거였어."],
        "m_source_confirm": ["그 관측, 내 거 맞아. 수정할 부분 없어."],
        "m_note_relay": ["출처가 둘이 아니었던 거야. {b} 한 사람이었고, 중간에 한 번 바뀌었어."]
    },
    "noa": {
        "m_heard": ["{via}한테 들은 말이에요. {time}쯤, {phrase} {room} 쪽으로. 제 눈으로 본 건 아니에요."],
        "m_heard_named": ["{via}한테 들었어요. {time}쯤 {target}. {room} 근처. 직접 본 건 아니에요."],
        "m_source_correct": ["그렇게 적으면 안 돼요. 제가 본 건 {phrase} {room} 쪽으로 가는 거였어요."],
        "m_source_confirm": ["맞아요. 제가 본 거예요. 그대로 적어도 돼요."],
        "m_note_relay": ["‘전언, 한 번 바뀜.’ …적어 둘게요. 출처는 {b} 한 사람이에요."]
    },
    "sena": {
        "m_heard": ["{via|i} 그랬어. {time}쯤 {phrase} {room} 쪽으로 갔대. 내가 본 건 아니야."],
        "m_heard_named": ["{via|i} {target|eul} 봤대. {time}쯤, {room} 근처. 난 전해 들은 거야."],
        "m_source_correct": ["그렇게 전해졌어? 틀렸어. 내가 본 건 {phrase} {room} 쪽으로 가는 거였어."],
        "m_source_confirm": ["내가 봤어. 그 말 맞아."]
    },
    "vale": {
        "m_heard": ["{via}한테 들었어요. {time}쯤 {phrase} {room} 쪽으로 갔다고요. 전해 들은 말이라 한 번 건너온 거예요."],
        "m_heard_named": ["{via|i} {target|eul} 봤다고 했어요. {time}쯤이요. 제가 들은 건 거기까지예요."],
        "m_source_correct": ["…말이 옮겨지면서 바뀌었어요. 제가 본 건 {phrase} {room} 쪽으로 가는 거였어요."],
        "m_source_confirm": ["네, 제가 본 게 맞아요. 바뀐 데 없이 전해졌어요."],
        "m_note_relay": ["신호도 한 번 중계를 거치면 잡음이 섞여요. 사람 말도 그래요. 처음 본 사람은 {b|ieyo}."]
    },
    "eli": {
        "m_heard": ["{via}한테 들었어. {time}, {phrase} {room} 방향. 내 관측은 아니야."],
        "m_heard_named": ["{via|i} {target|eul} 봤대. {time}. 전언이야."],
        "m_source_correct": ["틀렸어. 내가 본 건 {phrase} {room} 방향이었어."],
        "m_source_confirm": ["내 관측 맞아."]
    },
    "lyra": {
        "m_heard": ["{via|i} 그러던데요, {time}쯤 {phrase} {room} 쪽으로 갔대요. 저는 직접 못 봤어요."],
        "m_heard_named": ["{via|i} {target|eul} 봤다고 했어요. {time}쯤 {room} 근처에서요."],
        "m_source_correct": ["어머, 그렇게 전해졌어요? 제가 본 건 {phrase} {room} 쪽으로 가는 거였어요."],
        "m_source_confirm": ["네, 제가 본 거 맞아요."]
    }
}

# What someone says as the pod closes, by how they are taking it (§36) — not
# by what they are. A Null and an innocent can land in any of these states,
# so the words never settle the question on their own. resigned is the old
# single line; hurt names the close friend whose vote went against them;
# confused is for thin public reasons; at_player speaks to the explorer who
# pushed for it. {friend} is filled by the session.
const ISOLATED_STATE_LINES := {
    "mira": {"resigned": "…알겠어요. 제 기록이 끝까지 도움이 되길 바라요.",
        "hurt": "{friend}까지… 아니에요. 원망하는 게 아니에요. 그냥, 조금 아파서요.",
        "confused": "제가 뭘 놓쳤는지 모르겠어요. 확인된 것만 말했는데…",
        "at_player": "탐사요원님이 그렇게 봤다면… 이유가 있겠죠. 끝까지 보고 판단해 줘요."},
    "rho": {"resigned": "공구는 문 앞에 둘게. 펌프 소리 달라지면 바로 멈춰.",
        "hurt": "{friend}, 너까지 그쪽이야? …그래, 알았어.",
        "confused": "잠깐, 나 진짜 모르겠어. 그게 왜 나를 가리키는 건데?",
        "at_player": "야, 탐사요원. 틀렸으면 나중에 사과해. 맛있는 거로."},
    "dax": {"resigned": "내 판단도 틀릴 수 있어. 그러니까 기록은 지우지 마.",
        "hurt": "{friend}. 네 계산은 존중해. 결과가 마음에 안 들 뿐이야.",
        "confused": "변수가 하나 빠졌어. 그게 뭔지 모르는 채로 들어가는 건 처음이네.",
        "at_player": "근거를 끝까지 따라가. 내가 틀렸다면 그걸로 된 거고, 아니라면 거기서 다시 시작해."},
    "noa": {"resigned": "마지막 기록이에요. ‘나는 끝까지 말을 바꾸지 않았다.’",
        "hurt": "{friend}… 적어 둘게요. 아니, 이건 안 적을래요.",
        "confused": "제 기록 어디가 틀렸는지 알려 주세요. 고치고 싶어요.",
        "at_player": "제 메모 두고 가요. 판단은 기록 말고 탐사요원님이 해요."},
    "sena": {"resigned": "알았어. 문은 닫을게. 밖에 있는 사람들 잘 봐 줘.",
        "hurt": "{friend}. …됐어. 나 없어도 문 잠그는 거 잊지 마.",
        "confused": "내가 뭘 막았어야 했는데. …모르겠어. 이번엔 진짜 모르겠어.",
        "at_player": "탐사요원. 등 뒤 조심해. 이제 내가 없으니까."},
    "vale": {"resigned": "탐사요원님… 이게 정말 맞는 선택이길 바라요.",
        "hurt": "{friend}의 목소리였죠. 마지막 표… 들렸어요.",
        "confused": "제가 들은 것과 다들 들은 게 달랐나 봐요. 어디서 어긋났는지 모르겠어요.",
        "at_player": "…당신 목소리는 기억할게요. 잠들어도요."},
    "eli": {"resigned": "항로 사본은 남겼어. 좌표를 다시 확인해.",
        "hurt": "{friend}. 동선은 맞았는데. …사람은 계산이 안 되네.",
        "confused": "그 시각에 난 거기 없었어. 물리적으로. 그게 안 통하면 뭐가 통하는데.",
        "at_player": "시계 맞춰. 내 거 기준으로. 그거 하나만 부탁해."},
    "lyra": {"resigned": "괜찮아요… 다들, 서로를 너무 미워하지는 마요.",
        "hurt": "{friend}도요? …물은 제가 없어도 꼭 줘요.",
        "confused": "제가 뭘 잘못 봤을까요. 평소랑 다른 건 저였나 봐요.",
        "at_player": "탐사요원님, 새 잎 나면 봐 줘요. 약속이에요."}
}

static func isolated_line(npc_id: String, state: String, friend_name: String = "") -> String:
    var table: Dictionary = ISOLATED_STATE_LINES.get(npc_id, {})
    var text := str(table.get(state, table.get("resigned", "…")))
    return AstraJosa.fill(text, {"friend": friend_name})

# The morning after the shield turned an attack away (§39): the one who was
# targeted asks why, and anyone may doubt what the shield really caught.
const SHIELD_LINES := {
    "mira": {"m_why_me": ["어젯밤 제 문 앞에서 차폐막이 뭔가를 막았대요. …왜 저였을까요. 제가 뭘 알고 있다고 생각한 걸까요."],
        "m_doubt_shield": ["차폐막이 막은 게 꼭 공격이었는지는 모르잖아요. 기록엔 열 흔적만 남았어요."],
        "open_after_shielded": ["어젯밤 일, 들었죠? 제 문 앞이었대요. 누가 차폐막을 거기 뒀는지는 모르지만… 고마워요."]},
    "rho": {"m_why_me": ["야, 어젯밤 내 문 앞에서 차폐막이 뭘 막았대. 나 뭐 알고 있는 거 없는데? …없나?"],
        "m_doubt_shield": ["근데 차폐막에 걸린 게 공격인지 누가 확인했어? 그냥 누가 지나간 걸 수도 있잖아."],
        "open_after_shielded": ["어젯밤 차폐막, 내 문 앞이었다며. 누가 둔 건지 몰라도 한 턱 쏠게."]},
    "dax": {"m_why_me": ["어젯밤 목표는 나였어. 위협으로 계산됐다는 뜻이지. 내가 가진 변수 중에 뭐가 문제였을까."],
        "m_doubt_shield": ["차폐막 기록엔 열 흔적뿐이야. 공격이라는 건 해석이지 관측이 아니야."],
        "open_after_shielded": ["어젯밤 차폐막 위치, 결과적으로 정답이었어. 누가 골랐는지는 묻지 않을게."]},
    "noa": {"m_why_me": ["어젯밤 제 문이었대요. 제 기록 중에 누군가 지우고 싶은 게 있었던 거예요. 찾아볼게요."],
        "m_doubt_shield": ["기록상으로는 ‘차단’만 남았어요. ‘공격’이라고 적힌 건 없어요."],
        "open_after_shielded": ["어젯밤 기록, 제 선실 앞 차단. 적어 뒀어요. …고맙다는 말도 같이요."]},
    "sena": {"m_why_me": ["어젯밤 내 문 앞이었다며. 좋아. 그럼 내가 뭔가 제대로 보고 있었다는 거네."],
        "m_doubt_shield": ["문 앞에 누가 왔었다는 것만으로 그 사람이 깨끗하다는 뜻은 아니야."],
        "open_after_shielded": ["어젯밤 내 문 앞에 차폐막 둔 거, 너지? 빚졌네."]},
    "vale": {"m_why_me": ["…어젯밤 제 문 앞에서 소리가 났대요. 저는 못 들었어요. 그게 더 무서워요."],
        "m_doubt_shield": ["…막혔다는 소리만 남았어요. 누가, 왜였는지는 아무도 못 들었어요."],
        "open_after_shielded": ["…어젯밤이 조용했던 게 누구 덕분인지 알 것 같아요."]},
    "eli": {"m_why_me": ["어젯밤 내 선실. 동선상 거기까지 오려면 두 번 꺾어야 해. 작정하고 온 거야."],
        "m_doubt_shield": ["차폐막 반응이 곧 공격은 아니야. 동선부터 봐."],
        "open_after_shielded": ["어젯밤 내 선실 앞. 차폐막 위치 계산 잘했어."]},
    "lyra": {"m_why_me": ["제 문 앞이었다고요? …저는 화분 얘기밖에 안 했는데. 무슨 말이 걸렸을까요."],
        "m_doubt_shield": ["노려졌다는 말을 그대로 다 믿는 것도… 조금 위험하지 않을까요."],
        "open_after_shielded": ["어젯밤 제 문 앞이었대요. 무서웠지만… 누가 지켜 줬다는 게 이상하게 따뜻해요."]}
}

# ANALYST (§68): the person whose statement was put through the precise
# comparison reacts in their own voice. Sayable by anyone; never a verdict.
const ANALYST_LINES := {
    "mira": {"analyst_conflict": ["정밀 대조까지요? …좋아요. 그럼 저도 제 기억을 다시 볼게요."], "analyst_consistent": ["거봐요. 확인된 건 확인된 거예요."]},
    "rho": {"analyst_conflict": ["어, 그게 안 맞는다고? 잠깐만, 내가 시간 착각했나…"], "analyst_consistent": ["거 봐, 맞잖아. 기계는 거짓말 안 해."]},
    "dax": {"analyst_conflict": ["대조 결과는 존중해. 어느 변수가 틀렸는지는 따로 보자."], "analyst_consistent": ["예상대로야. 조건이 맞으면 결과도 맞아."]},
    "noa": {"analyst_conflict": ["…어긋난다고요. 적어 둘게요. 제 문장이 틀렸을 수도 있으니까요."], "analyst_consistent": ["일치. 적어 둘게요."]},
    "sena": {"analyst_conflict": ["그래서? 안 맞는다고 해서 바로 나라는 건 아니잖아."], "analyst_consistent": ["봤지. 문은 거짓말 안 한다니까."]},
    "vale": {"analyst_conflict": ["…간격이 안 맞는군요. 제가 들은 순서가 틀렸을 수도 있어요."], "analyst_consistent": ["…다행이에요. 제가 들은 게 맞았네요."]},
    "eli": {"analyst_conflict": ["물리적으로 안 맞는다는 거지. 다시 그려 볼게."], "analyst_consistent": ["맞아. 좌표대로야."]},
    "lyra": {"analyst_conflict": ["어머… 제가 뭘 잘못 말했나 봐요. 다시 생각해 볼게요."], "analyst_consistent": ["다행이다. 제 말이 맞았네요."]}
}
